/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type PropertiesControllerFindManyParams = {
propertyTypeId: string;
transactionType: string;
businessStatus: string;
publicationStatus: string;
provinceId: string;
districtId: string;
wardId: string;
projectId: string;
zoneId: string;
minPrice: string;
maxPrice: string;
minArea: string;
maxArea: string;
search: string;
limit: string;
offset: string;
};
