/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateContactRequestDto,
  GetApiContactRequestsParams,
  UpdateContactRequestDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary Submit a general contact request (public)
 */
export const postApiContactRequests = (
    createContactRequestDto: CreateContactRequestDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/contact-requests`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createContactRequestDto, signal
    },
      );
    }
  


export const getPostApiContactRequestsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiContactRequests>>, TError,{data: CreateContactRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiContactRequests>>, TError,{data: CreateContactRequestDto}, TContext> => {

const mutationKey = ['postApiContactRequests'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiContactRequests>>, {data: CreateContactRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiContactRequests(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiContactRequestsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiContactRequests>>>
    export type PostApiContactRequestsMutationBody = CreateContactRequestDto
    export type PostApiContactRequestsMutationError = unknown

    /**
 * @summary Submit a general contact request (public)
 */
export const usePostApiContactRequests = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiContactRequests>>, TError,{data: CreateContactRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiContactRequests>>,
        TError,
        {data: CreateContactRequestDto},
        TContext
      > => {

      const mutationOptions = getPostApiContactRequestsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List contact requests (admin only)
 */
export const getApiContactRequests = (
    params?: GetApiContactRequestsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/contact-requests`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiContactRequestsInfiniteQueryKey = (params?: GetApiContactRequestsParams,) => {
    return [
    'infinite', `/api/contact-requests`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiContactRequestsQueryKey = (params?: GetApiContactRequestsParams,) => {
    return [
    `/api/contact-requests`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiContactRequestsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequests>>>, TError = unknown>(params?: GetApiContactRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactRequestsInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactRequests>>> = ({ signal }) => getApiContactRequests(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactRequestsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactRequests>>>
export type GetApiContactRequestsInfiniteQueryError = unknown


export function useGetApiContactRequestsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequests>>>, TError = unknown>(
 params: undefined |  GetApiContactRequestsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactRequests>>,
          TError,
          Awaited<ReturnType<typeof getApiContactRequests>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactRequestsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequests>>>, TError = unknown>(
 params?: GetApiContactRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactRequests>>,
          TError,
          Awaited<ReturnType<typeof getApiContactRequests>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactRequestsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequests>>>, TError = unknown>(
 params?: GetApiContactRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List contact requests (admin only)
 */

export function useGetApiContactRequestsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequests>>>, TError = unknown>(
 params?: GetApiContactRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactRequestsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List contact requests (admin only)
 */
export const prefetchGetApiContactRequestsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiContactRequests>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiContactRequestsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactRequestsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiContactRequestsQueryOptions = <TData = Awaited<ReturnType<typeof getApiContactRequests>>, TError = unknown>(params?: GetApiContactRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactRequestsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactRequests>>> = ({ signal }) => getApiContactRequests(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactRequests>>>
export type GetApiContactRequestsQueryError = unknown


export function useGetApiContactRequests<TData = Awaited<ReturnType<typeof getApiContactRequests>>, TError = unknown>(
 params: undefined |  GetApiContactRequestsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactRequests>>,
          TError,
          Awaited<ReturnType<typeof getApiContactRequests>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactRequests<TData = Awaited<ReturnType<typeof getApiContactRequests>>, TError = unknown>(
 params?: GetApiContactRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactRequests>>,
          TError,
          Awaited<ReturnType<typeof getApiContactRequests>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactRequests<TData = Awaited<ReturnType<typeof getApiContactRequests>>, TError = unknown>(
 params?: GetApiContactRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List contact requests (admin only)
 */

export function useGetApiContactRequests<TData = Awaited<ReturnType<typeof getApiContactRequests>>, TError = unknown>(
 params?: GetApiContactRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactRequestsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List contact requests (admin only)
 */
export const prefetchGetApiContactRequestsQuery = async <TData = Awaited<ReturnType<typeof getApiContactRequests>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiContactRequestsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequests>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactRequestsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Get a contact request by ID
 */
export const getApiContactRequestsId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/contact-requests/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiContactRequestsIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/contact-requests/${id}`
    ] as const;
    }

export const getGetApiContactRequestsIdQueryKey = (id?: string,) => {
    return [
    `/api/contact-requests/${id}`
    ] as const;
    }

    
export const getGetApiContactRequestsIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequestsId>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactRequestsIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactRequestsId>>> = ({ signal }) => getApiContactRequestsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactRequestsIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactRequestsId>>>
export type GetApiContactRequestsIdInfiniteQueryError = unknown


export function useGetApiContactRequestsIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequestsId>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactRequestsId>>,
          TError,
          Awaited<ReturnType<typeof getApiContactRequestsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactRequestsIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequestsId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactRequestsId>>,
          TError,
          Awaited<ReturnType<typeof getApiContactRequestsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactRequestsIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequestsId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a contact request by ID
 */

export function useGetApiContactRequestsIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiContactRequestsId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactRequestsIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get a contact request by ID
 */
export const prefetchGetApiContactRequestsIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiContactRequestsId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactRequestsIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiContactRequestsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiContactRequestsId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiContactRequestsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiContactRequestsId>>> = ({ signal }) => getApiContactRequestsId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiContactRequestsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiContactRequestsId>>>
export type GetApiContactRequestsIdQueryError = unknown


export function useGetApiContactRequestsId<TData = Awaited<ReturnType<typeof getApiContactRequestsId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactRequestsId>>,
          TError,
          Awaited<ReturnType<typeof getApiContactRequestsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactRequestsId<TData = Awaited<ReturnType<typeof getApiContactRequestsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiContactRequestsId>>,
          TError,
          Awaited<ReturnType<typeof getApiContactRequestsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiContactRequestsId<TData = Awaited<ReturnType<typeof getApiContactRequestsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a contact request by ID
 */

export function useGetApiContactRequestsId<TData = Awaited<ReturnType<typeof getApiContactRequestsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiContactRequestsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get a contact request by ID
 */
export const prefetchGetApiContactRequestsIdQuery = async <TData = Awaited<ReturnType<typeof getApiContactRequestsId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiContactRequestsId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiContactRequestsIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update a contact request (status/reply)
 */
export const patchApiContactRequestsId = (
    id: string,
    updateContactRequestDto: UpdateContactRequestDto,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/contact-requests/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateContactRequestDto
    },
      );
    }
  


export const getPatchApiContactRequestsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiContactRequestsId>>, TError,{id: string;data: UpdateContactRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiContactRequestsId>>, TError,{id: string;data: UpdateContactRequestDto}, TContext> => {

const mutationKey = ['patchApiContactRequestsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiContactRequestsId>>, {id: string;data: UpdateContactRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiContactRequestsId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiContactRequestsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiContactRequestsId>>>
    export type PatchApiContactRequestsIdMutationBody = UpdateContactRequestDto
    export type PatchApiContactRequestsIdMutationError = unknown

    /**
 * @summary Update a contact request (status/reply)
 */
export const usePatchApiContactRequestsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiContactRequestsId>>, TError,{id: string;data: UpdateContactRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiContactRequestsId>>,
        TError,
        {id: string;data: UpdateContactRequestDto},
        TContext
      > => {

      const mutationOptions = getPatchApiContactRequestsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Archive a contact request
 */
export const deleteApiContactRequestsId = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/api/contact-requests/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiContactRequestsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiContactRequestsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiContactRequestsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiContactRequestsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiContactRequestsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiContactRequestsId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiContactRequestsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiContactRequestsId>>>
    
    export type DeleteApiContactRequestsIdMutationError = unknown

    /**
 * @summary Archive a contact request
 */
export const useDeleteApiContactRequestsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiContactRequestsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiContactRequestsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiContactRequestsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    