/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCustomerDto,
  CreateCustomerNeedDto,
  GetApiCustomerNeedsParams,
  GetApiCustomersParams,
  UpdateCustomerDto
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiCustomersResponse200 = {
  data: void
  status: 200
}

export type getApiCustomersResponseSuccess = (getApiCustomersResponse200) & {
  headers: Headers;
};
;

export type getApiCustomersResponse = (getApiCustomersResponseSuccess)

export const getGetApiCustomersUrl = (params: GetApiCustomersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/customers?${stringifiedParams}` : `/api/v1/customers`
}

/**
 * @summary List customers with filters
 */
export const getApiCustomers = async (params: GetApiCustomersParams, options?: RequestInit): Promise<getApiCustomersResponse> => {

  return useCustomClient<getApiCustomersResponse>(getGetApiCustomersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCustomersInfiniteQueryKey = (params?: GetApiCustomersParams,) => {
    return [
    'infinite', `/api/v1/customers`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetApiCustomersQueryKey = (params?: GetApiCustomersParams,) => {
    return [
    `/api/v1/customers`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCustomersInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = ErrorType<unknown>>(params: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomers>>> = ({ signal }) => getApiCustomers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomers>>>
export type GetApiCustomersInfiniteQueryError = ErrorType<unknown>


export function useGetApiCustomersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = ErrorType<unknown>>(
 params: GetApiCustomersParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomers>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = ErrorType<unknown>>(
 params: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomers>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = ErrorType<unknown>>(
 params: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customers with filters
 */

export function useGetApiCustomersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomers>>>, TError = ErrorType<unknown>>(
 params: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List customers with filters
 */
export const prefetchGetApiCustomersInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params: GetApiCustomersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiCustomersQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = ErrorType<unknown>>(params: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomers>>> = ({ signal }) => getApiCustomers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomers>>>
export type GetApiCustomersQueryError = ErrorType<unknown>


export function useGetApiCustomers<TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = ErrorType<unknown>>(
 params: GetApiCustomersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomers>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomers<TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = ErrorType<unknown>>(
 params: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomers>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomers<TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = ErrorType<unknown>>(
 params: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customers with filters
 */

export function useGetApiCustomers<TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = ErrorType<unknown>>(
 params: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List customers with filters
 */
export const prefetchGetApiCustomersQuery = async <TData = Awaited<ReturnType<typeof getApiCustomers>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params: GetApiCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomers>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomersQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiCustomerResponse201 = {
  data: void
  status: 201
}

export type postApiCustomerResponseSuccess = (postApiCustomerResponse201) & {
  headers: Headers;
};
;

export type postApiCustomerResponse = (postApiCustomerResponseSuccess)

export const getPostApiCustomerUrl = () => {




  return `/api/v1/customers`
}

/**
 * @summary Create a customer
 */
export const postApiCustomer = async (createCustomerDto: CreateCustomerDto, options?: RequestInit): Promise<postApiCustomerResponse> => {

  return useCustomClient<postApiCustomerResponse>(getPostApiCustomerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCustomerDto)
  }
);}





export const getPostApiCustomerMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomer>>, TError,{data: BodyType<CreateCustomerDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCustomer>>, TError,{data: BodyType<CreateCustomerDto>}, TContext> => {

const mutationKey = ['postApiCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCustomer>>, {data: BodyType<CreateCustomerDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiCustomer(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCustomer>>>
    export type PostApiCustomerMutationBody = BodyType<CreateCustomerDto>
    export type PostApiCustomerMutationError = ErrorType<unknown>

    /**
 * @summary Create a customer
 */
export const usePostApiCustomer = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomer>>, TError,{data: BodyType<CreateCustomerDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCustomer>>,
        TError,
        {data: BodyType<CreateCustomerDto>},
        TContext
      > => {
      return useMutation(getPostApiCustomerMutationOptions(options), queryClient);
    }
    export type getApiCustomerIdResponse200 = {
  data: void
  status: 200
}

export type getApiCustomerIdResponseSuccess = (getApiCustomerIdResponse200) & {
  headers: Headers;
};
;

export type getApiCustomerIdResponse = (getApiCustomerIdResponseSuccess)

export const getGetApiCustomerIdUrl = (id: string,) => {




  return `/api/v1/customers/${id}`
}

/**
 * @summary Get customer by ID
 */
export const getApiCustomerId = async (id: string, options?: RequestInit): Promise<getApiCustomerIdResponse> => {

  return useCustomClient<getApiCustomerIdResponse>(getGetApiCustomerIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCustomerIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/v1/customers/${id}`
    ] as const;
    }

export const getGetApiCustomerIdQueryKey = (id: string,) => {
    return [
    `/api/v1/customers/${id}`
    ] as const;
    }


export const getGetApiCustomerIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerIdInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerId>>> = ({ signal }) => getApiCustomerId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerId>>>
export type GetApiCustomerIdInfiniteQueryError = ErrorType<unknown>


export function useGetApiCustomerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get customer by ID
 */

export function useGetApiCustomerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get customer by ID
 */
export const prefetchGetApiCustomerIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiCustomerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerId>>> = ({ signal }) => getApiCustomerId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerId>>>
export type GetApiCustomerIdQueryError = ErrorType<unknown>


export function useGetApiCustomerId<TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerId<TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerId<TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get customer by ID
 */

export function useGetApiCustomerId<TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get customer by ID
 */
export const prefetchGetApiCustomerIdQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type patchApiCustomerResponse200 = {
  data: void
  status: 200
}

export type patchApiCustomerResponseSuccess = (patchApiCustomerResponse200) & {
  headers: Headers;
};
;

export type patchApiCustomerResponse = (patchApiCustomerResponseSuccess)

export const getPatchApiCustomerUrl = (id: string,) => {




  return `/api/v1/customers/${id}`
}

/**
 * @summary Update a customer
 */
export const patchApiCustomer = async (id: string,
    updateCustomerDto: UpdateCustomerDto, options?: RequestInit): Promise<patchApiCustomerResponse> => {

  return useCustomClient<patchApiCustomerResponse>(getPatchApiCustomerUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCustomerDto)
  }
);}





export const getPatchApiCustomerMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCustomer>>, TError,{id: string;data: BodyType<UpdateCustomerDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiCustomer>>, TError,{id: string;data: BodyType<UpdateCustomerDto>}, TContext> => {

const mutationKey = ['patchApiCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiCustomer>>, {id: string;data: BodyType<UpdateCustomerDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiCustomer(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiCustomer>>>
    export type PatchApiCustomerMutationBody = BodyType<UpdateCustomerDto>
    export type PatchApiCustomerMutationError = ErrorType<unknown>

    /**
 * @summary Update a customer
 */
export const usePatchApiCustomer = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCustomer>>, TError,{id: string;data: BodyType<UpdateCustomerDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiCustomer>>,
        TError,
        {id: string;data: BodyType<UpdateCustomerDto>},
        TContext
      > => {
      return useMutation(getPatchApiCustomerMutationOptions(options), queryClient);
    }
    export type deleteApiCustomerResponse200 = {
  data: void
  status: 200
}

export type deleteApiCustomerResponseSuccess = (deleteApiCustomerResponse200) & {
  headers: Headers;
};
;

export type deleteApiCustomerResponse = (deleteApiCustomerResponseSuccess)

export const getDeleteApiCustomerUrl = (id: string,) => {




  return `/api/v1/customers/${id}`
}

/**
 * @summary Soft delete a customer
 */
export const deleteApiCustomer = async (id: string, options?: RequestInit): Promise<deleteApiCustomerResponse> => {

  return useCustomClient<deleteApiCustomerResponse>(getDeleteApiCustomerUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiCustomerMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCustomer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCustomer>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiCustomer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCustomer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCustomer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCustomer>>>

    export type DeleteApiCustomerMutationError = ErrorType<unknown>

    /**
 * @summary Soft delete a customer
 */
export const useDeleteApiCustomer = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCustomer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCustomer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiCustomerMutationOptions(options), queryClient);
    }
    export type getApiCustomerNeedsResponse200 = {
  data: void
  status: 200
}

export type getApiCustomerNeedsResponseSuccess = (getApiCustomerNeedsResponse200) & {
  headers: Headers;
};
;

export type getApiCustomerNeedsResponse = (getApiCustomerNeedsResponseSuccess)

export const getGetApiCustomerNeedsUrl = (params: GetApiCustomerNeedsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/customer-needs?${stringifiedParams}` : `/api/v1/customer-needs`
}

/**
 * @summary List customer needs
 */
export const getApiCustomerNeeds = async (params: GetApiCustomerNeedsParams, options?: RequestInit): Promise<getApiCustomerNeedsResponse> => {

  return useCustomClient<getApiCustomerNeedsResponse>(getGetApiCustomerNeedsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiCustomerNeedsInfiniteQueryKey = (params?: GetApiCustomerNeedsParams,) => {
    return [
    'infinite', `/api/v1/customer-needs`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetApiCustomerNeedsQueryKey = (params?: GetApiCustomerNeedsParams,) => {
    return [
    `/api/v1/customer-needs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiCustomerNeedsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = ErrorType<unknown>>(params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerNeedsInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerNeeds>>> = ({ signal }) => getApiCustomerNeeds(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerNeedsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerNeeds>>>
export type GetApiCustomerNeedsInfiniteQueryError = ErrorType<unknown>


export function useGetApiCustomerNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = ErrorType<unknown>>(
 params: GetApiCustomerNeedsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeeds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = ErrorType<unknown>>(
 params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeeds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = ErrorType<unknown>>(
 params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customer needs
 */

export function useGetApiCustomerNeedsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCustomerNeeds>>>, TError = ErrorType<unknown>>(
 params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerNeedsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List customer needs
 */
export const prefetchGetApiCustomerNeedsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerNeedsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiCustomerNeedsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = ErrorType<unknown>>(params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCustomerNeedsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCustomerNeeds>>> = ({ signal }) => getApiCustomerNeeds(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCustomerNeedsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCustomerNeeds>>>
export type GetApiCustomerNeedsQueryError = ErrorType<unknown>


export function useGetApiCustomerNeeds<TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = ErrorType<unknown>>(
 params: GetApiCustomerNeedsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeeds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeeds<TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = ErrorType<unknown>>(
 params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCustomerNeeds>>,
          TError,
          Awaited<ReturnType<typeof getApiCustomerNeeds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCustomerNeeds<TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = ErrorType<unknown>>(
 params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customer needs
 */

export function useGetApiCustomerNeeds<TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = ErrorType<unknown>>(
 params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCustomerNeedsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List customer needs
 */
export const prefetchGetApiCustomerNeedsQuery = async <TData = Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params: GetApiCustomerNeedsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCustomerNeeds>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCustomerNeedsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiCustomerNeedResponse201 = {
  data: void
  status: 201
}

export type postApiCustomerNeedResponseSuccess = (postApiCustomerNeedResponse201) & {
  headers: Headers;
};
;

export type postApiCustomerNeedResponse = (postApiCustomerNeedResponseSuccess)

export const getPostApiCustomerNeedUrl = () => {




  return `/api/v1/customer-needs`
}

/**
 * @summary Create a customer need
 */
export const postApiCustomerNeed = async (createCustomerNeedDto: CreateCustomerNeedDto, options?: RequestInit): Promise<postApiCustomerNeedResponse> => {

  return useCustomClient<postApiCustomerNeedResponse>(getPostApiCustomerNeedUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCustomerNeedDto)
  }
);}





export const getPostApiCustomerNeedMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeed>>, TError,{data: BodyType<CreateCustomerNeedDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeed>>, TError,{data: BodyType<CreateCustomerNeedDto>}, TContext> => {

const mutationKey = ['postApiCustomerNeed'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCustomerNeed>>, {data: BodyType<CreateCustomerNeedDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiCustomerNeed(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCustomerNeedMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCustomerNeed>>>
    export type PostApiCustomerNeedMutationBody = BodyType<CreateCustomerNeedDto>
    export type PostApiCustomerNeedMutationError = ErrorType<unknown>

    /**
 * @summary Create a customer need
 */
export const usePostApiCustomerNeed = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCustomerNeed>>, TError,{data: BodyType<CreateCustomerNeedDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCustomerNeed>>,
        TError,
        {data: BodyType<CreateCustomerNeedDto>},
        TContext
      > => {
      return useMutation(getPostApiCustomerNeedMutationOptions(options), queryClient);
    }
