/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateDealActivityDto,
  CreateDealDto,
  CreateReservationDto,
  GetApiDealsParams,
  GetApiReservationsParams,
  UpdateDealDto
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiDealsResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiDealsResponseError = (getApiDealsResponseDefault) & {
  headers: Headers;
};

export type getApiDealsResponse = (getApiDealsResponseError)

export const getGetApiDealsUrl = (params?: GetApiDealsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/deals?${stringifiedParams}` : `/api/v1/deals`
}

/**
 * @summary List deals
 */
export const getApiDeals = async (params?: GetApiDealsParams, options?: RequestInit): Promise<getApiDealsResponse> => {

  return useCustomClient<getApiDealsResponse>(getGetApiDealsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiDealsInfiniteQueryKey = (params?: GetApiDealsParams,) => {
    return [
    'infinite', `/api/v1/deals`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetApiDealsQueryKey = (params?: GetApiDealsParams,) => {
    return [
    `/api/v1/deals`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiDealsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiDeals>>>, TError = ErrorType<unknown>>(params?: GetApiDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDealsInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDeals>>> = ({ signal }) => getApiDeals(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDealsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDeals>>>
export type GetApiDealsInfiniteQueryError = ErrorType<unknown>


export function useGetApiDealsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDeals>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiDealsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDeals>>,
          TError,
          Awaited<ReturnType<typeof getApiDeals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDeals>>>, TError = ErrorType<unknown>>(
 params?: GetApiDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDeals>>,
          TError,
          Awaited<ReturnType<typeof getApiDeals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDeals>>>, TError = ErrorType<unknown>>(
 params?: GetApiDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List deals
 */

export function useGetApiDealsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDeals>>>, TError = ErrorType<unknown>>(
 params?: GetApiDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDealsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List deals
 */
export const prefetchGetApiDealsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiDeals>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiDealsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiDealsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiDealsQueryOptions = <TData = Awaited<ReturnType<typeof getApiDeals>>, TError = ErrorType<unknown>>(params?: GetApiDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDealsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDeals>>> = ({ signal }) => getApiDeals(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDealsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDeals>>>
export type GetApiDealsQueryError = ErrorType<unknown>


export function useGetApiDeals<TData = Awaited<ReturnType<typeof getApiDeals>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiDealsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDeals>>,
          TError,
          Awaited<ReturnType<typeof getApiDeals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDeals<TData = Awaited<ReturnType<typeof getApiDeals>>, TError = ErrorType<unknown>>(
 params?: GetApiDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDeals>>,
          TError,
          Awaited<ReturnType<typeof getApiDeals>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDeals<TData = Awaited<ReturnType<typeof getApiDeals>>, TError = ErrorType<unknown>>(
 params?: GetApiDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List deals
 */

export function useGetApiDeals<TData = Awaited<ReturnType<typeof getApiDeals>>, TError = ErrorType<unknown>>(
 params?: GetApiDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDealsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List deals
 */
export const prefetchGetApiDealsQuery = async <TData = Awaited<ReturnType<typeof getApiDeals>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiDealsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDeals>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiDealsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiDealResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiDealResponseError = (postApiDealResponseDefault) & {
  headers: Headers;
};

export type postApiDealResponse = (postApiDealResponseError)

export const getPostApiDealUrl = () => {




  return `/api/v1/deals`
}

/**
 * @summary Create a deal
 */
export const postApiDeal = async (createDealDto: CreateDealDto, options?: RequestInit): Promise<postApiDealResponse> => {

  return useCustomClient<postApiDealResponse>(getPostApiDealUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createDealDto)
  }
);}





export const getPostApiDealMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiDeal>>, TError,{data: BodyType<CreateDealDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiDeal>>, TError,{data: BodyType<CreateDealDto>}, TContext> => {

const mutationKey = ['postApiDeal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiDeal>>, {data: BodyType<CreateDealDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiDeal(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiDealMutationResult = NonNullable<Awaited<ReturnType<typeof postApiDeal>>>
    export type PostApiDealMutationBody = BodyType<CreateDealDto>
    export type PostApiDealMutationError = ErrorType<unknown>

    /**
 * @summary Create a deal
 */
export const usePostApiDeal = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiDeal>>, TError,{data: BodyType<CreateDealDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiDeal>>,
        TError,
        {data: BodyType<CreateDealDto>},
        TContext
      > => {
      return useMutation(getPostApiDealMutationOptions(options), queryClient);
    }
    export type getApiDealIdResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiDealIdResponseError = (getApiDealIdResponseDefault) & {
  headers: Headers;
};

export type getApiDealIdResponse = (getApiDealIdResponseError)

export const getGetApiDealIdUrl = (id: string,) => {




  return `/api/v1/deals/${id}`
}

/**
 * @summary Get deal by ID
 */
export const getApiDealId = async (id: string, options?: RequestInit): Promise<getApiDealIdResponse> => {

  return useCustomClient<getApiDealIdResponse>(getGetApiDealIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiDealIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/v1/deals/${id}`
    ] as const;
    }

export const getGetApiDealIdQueryKey = (id: string,) => {
    return [
    `/api/v1/deals/${id}`
    ] as const;
    }


export const getGetApiDealIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiDealId>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDealIdInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDealId>>> = ({ signal }) => getApiDealId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDealIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDealId>>>
export type GetApiDealIdInfiniteQueryError = ErrorType<unknown>


export function useGetApiDealIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDealId>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDealId>>,
          TError,
          Awaited<ReturnType<typeof getApiDealId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDealId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDealId>>,
          TError,
          Awaited<ReturnType<typeof getApiDealId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDealId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get deal by ID
 */

export function useGetApiDealIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDealId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDealIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get deal by ID
 */
export const prefetchGetApiDealIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiDealId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiDealIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiDealIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiDealId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDealIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDealId>>> = ({ signal }) => getApiDealId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDealIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDealId>>>
export type GetApiDealIdQueryError = ErrorType<unknown>


export function useGetApiDealId<TData = Awaited<ReturnType<typeof getApiDealId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDealId>>,
          TError,
          Awaited<ReturnType<typeof getApiDealId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealId<TData = Awaited<ReturnType<typeof getApiDealId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDealId>>,
          TError,
          Awaited<ReturnType<typeof getApiDealId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealId<TData = Awaited<ReturnType<typeof getApiDealId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get deal by ID
 */

export function useGetApiDealId<TData = Awaited<ReturnType<typeof getApiDealId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDealIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get deal by ID
 */
export const prefetchGetApiDealIdQuery = async <TData = Awaited<ReturnType<typeof getApiDealId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiDealIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type patchApiDealResponseDefault = {
  data: unknown
  status: number
}

;
export type patchApiDealResponseError = (patchApiDealResponseDefault) & {
  headers: Headers;
};

export type patchApiDealResponse = (patchApiDealResponseError)

export const getPatchApiDealUrl = (id: string,) => {




  return `/api/v1/deals/${id}`
}

/**
 * @summary Update a deal
 */
export const patchApiDeal = async (id: string,
    updateDealDto: UpdateDealDto, options?: RequestInit): Promise<patchApiDealResponse> => {

  return useCustomClient<patchApiDealResponse>(getPatchApiDealUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateDealDto)
  }
);}





export const getPatchApiDealMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiDeal>>, TError,{id: string;data: BodyType<UpdateDealDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiDeal>>, TError,{id: string;data: BodyType<UpdateDealDto>}, TContext> => {

const mutationKey = ['patchApiDeal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiDeal>>, {id: string;data: BodyType<UpdateDealDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiDeal(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiDealMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiDeal>>>
    export type PatchApiDealMutationBody = BodyType<UpdateDealDto>
    export type PatchApiDealMutationError = ErrorType<unknown>

    /**
 * @summary Update a deal
 */
export const usePatchApiDeal = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiDeal>>, TError,{id: string;data: BodyType<UpdateDealDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiDeal>>,
        TError,
        {id: string;data: BodyType<UpdateDealDto>},
        TContext
      > => {
      return useMutation(getPatchApiDealMutationOptions(options), queryClient);
    }
    export type deleteApiDealResponseDefault = {
  data: unknown
  status: number
}

;
export type deleteApiDealResponseError = (deleteApiDealResponseDefault) & {
  headers: Headers;
};

export type deleteApiDealResponse = (deleteApiDealResponseError)

export const getDeleteApiDealUrl = (id: string,) => {




  return `/api/v1/deals/${id}`
}

/**
 * @summary Soft delete a deal
 */
export const deleteApiDeal = async (id: string, options?: RequestInit): Promise<deleteApiDealResponse> => {

  return useCustomClient<deleteApiDealResponse>(getDeleteApiDealUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiDealMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiDeal>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiDeal>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiDeal'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiDeal>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiDeal(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiDealMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiDeal>>>

    export type DeleteApiDealMutationError = ErrorType<unknown>

    /**
 * @summary Soft delete a deal
 */
export const useDeleteApiDeal = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiDeal>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiDeal>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiDealMutationOptions(options), queryClient);
    }
    export type getApiDealActivitiesResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiDealActivitiesResponseError = (getApiDealActivitiesResponseDefault) & {
  headers: Headers;
};

export type getApiDealActivitiesResponse = (getApiDealActivitiesResponseError)

export const getGetApiDealActivitiesUrl = (id: string,) => {




  return `/api/v1/deals/${id}/activities`
}

/**
 * @summary List activities for a deal
 */
export const getApiDealActivities = async (id: string, options?: RequestInit): Promise<getApiDealActivitiesResponse> => {

  return useCustomClient<getApiDealActivitiesResponse>(getGetApiDealActivitiesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiDealActivitiesInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/v1/deals/${id}/activities`
    ] as const;
    }

export const getGetApiDealActivitiesQueryKey = (id: string,) => {
    return [
    `/api/v1/deals/${id}/activities`
    ] as const;
    }


export const getGetApiDealActivitiesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiDealActivities>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDealActivitiesInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDealActivities>>> = ({ signal }) => getApiDealActivities(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDealActivitiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDealActivities>>>
export type GetApiDealActivitiesInfiniteQueryError = ErrorType<unknown>


export function useGetApiDealActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDealActivities>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDealActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiDealActivities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDealActivities>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDealActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiDealActivities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDealActivities>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List activities for a deal
 */

export function useGetApiDealActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiDealActivities>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDealActivitiesInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List activities for a deal
 */
export const prefetchGetApiDealActivitiesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiDealActivities>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiDealActivitiesInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiDealActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getApiDealActivities>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiDealActivitiesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiDealActivities>>> = ({ signal }) => getApiDealActivities(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiDealActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiDealActivities>>>
export type GetApiDealActivitiesQueryError = ErrorType<unknown>


export function useGetApiDealActivities<TData = Awaited<ReturnType<typeof getApiDealActivities>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDealActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiDealActivities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealActivities<TData = Awaited<ReturnType<typeof getApiDealActivities>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDealActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiDealActivities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiDealActivities<TData = Awaited<ReturnType<typeof getApiDealActivities>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List activities for a deal
 */

export function useGetApiDealActivities<TData = Awaited<ReturnType<typeof getApiDealActivities>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiDealActivitiesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List activities for a deal
 */
export const prefetchGetApiDealActivitiesQuery = async <TData = Awaited<ReturnType<typeof getApiDealActivities>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiDealActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiDealActivitiesQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiDealActivityResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiDealActivityResponseError = (postApiDealActivityResponseDefault) & {
  headers: Headers;
};

export type postApiDealActivityResponse = (postApiDealActivityResponseError)

export const getPostApiDealActivityUrl = (id: string,) => {




  return `/api/v1/deals/${id}/activities`
}

/**
 * @summary Add an activity to a deal
 */
export const postApiDealActivity = async (id: string,
    createDealActivityDto: CreateDealActivityDto, options?: RequestInit): Promise<postApiDealActivityResponse> => {

  return useCustomClient<postApiDealActivityResponse>(getPostApiDealActivityUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createDealActivityDto)
  }
);}





export const getPostApiDealActivityMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiDealActivity>>, TError,{id: string;data: BodyType<CreateDealActivityDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiDealActivity>>, TError,{id: string;data: BodyType<CreateDealActivityDto>}, TContext> => {

const mutationKey = ['postApiDealActivity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiDealActivity>>, {id: string;data: BodyType<CreateDealActivityDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiDealActivity(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiDealActivityMutationResult = NonNullable<Awaited<ReturnType<typeof postApiDealActivity>>>
    export type PostApiDealActivityMutationBody = BodyType<CreateDealActivityDto>
    export type PostApiDealActivityMutationError = ErrorType<unknown>

    /**
 * @summary Add an activity to a deal
 */
export const usePostApiDealActivity = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiDealActivity>>, TError,{id: string;data: BodyType<CreateDealActivityDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiDealActivity>>,
        TError,
        {id: string;data: BodyType<CreateDealActivityDto>},
        TContext
      > => {
      return useMutation(getPostApiDealActivityMutationOptions(options), queryClient);
    }
    export type getApiReservationsResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiReservationsResponseError = (getApiReservationsResponseDefault) & {
  headers: Headers;
};

export type getApiReservationsResponse = (getApiReservationsResponseError)

export const getGetApiReservationsUrl = (params?: GetApiReservationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/reservations?${stringifiedParams}` : `/api/v1/reservations`
}

/**
 * @summary List reservations
 */
export const getApiReservations = async (params?: GetApiReservationsParams, options?: RequestInit): Promise<getApiReservationsResponse> => {

  return useCustomClient<getApiReservationsResponse>(getGetApiReservationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiReservationsInfiniteQueryKey = (params?: GetApiReservationsParams,) => {
    return [
    'infinite', `/api/v1/reservations`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetApiReservationsQueryKey = (params?: GetApiReservationsParams,) => {
    return [
    `/api/v1/reservations`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiReservationsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiReservations>>>, TError = ErrorType<unknown>>(params?: GetApiReservationsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReservationsInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReservations>>> = ({ signal }) => getApiReservations(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReservationsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReservations>>>
export type GetApiReservationsInfiniteQueryError = ErrorType<unknown>


export function useGetApiReservationsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiReservations>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiReservationsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReservations>>,
          TError,
          Awaited<ReturnType<typeof getApiReservations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReservationsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiReservations>>>, TError = ErrorType<unknown>>(
 params?: GetApiReservationsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReservations>>,
          TError,
          Awaited<ReturnType<typeof getApiReservations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReservationsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiReservations>>>, TError = ErrorType<unknown>>(
 params?: GetApiReservationsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List reservations
 */

export function useGetApiReservationsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiReservations>>>, TError = ErrorType<unknown>>(
 params?: GetApiReservationsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReservationsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List reservations
 */
export const prefetchGetApiReservationsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiReservations>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiReservationsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiReservationsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiReservationsQueryOptions = <TData = Awaited<ReturnType<typeof getApiReservations>>, TError = ErrorType<unknown>>(params?: GetApiReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiReservationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiReservations>>> = ({ signal }) => getApiReservations(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiReservationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReservations>>>
export type GetApiReservationsQueryError = ErrorType<unknown>


export function useGetApiReservations<TData = Awaited<ReturnType<typeof getApiReservations>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiReservationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReservations>>,
          TError,
          Awaited<ReturnType<typeof getApiReservations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReservations<TData = Awaited<ReturnType<typeof getApiReservations>>, TError = ErrorType<unknown>>(
 params?: GetApiReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiReservations>>,
          TError,
          Awaited<ReturnType<typeof getApiReservations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiReservations<TData = Awaited<ReturnType<typeof getApiReservations>>, TError = ErrorType<unknown>>(
 params?: GetApiReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List reservations
 */

export function useGetApiReservations<TData = Awaited<ReturnType<typeof getApiReservations>>, TError = ErrorType<unknown>>(
 params?: GetApiReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiReservationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List reservations
 */
export const prefetchGetApiReservationsQuery = async <TData = Awaited<ReturnType<typeof getApiReservations>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiReservations>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiReservationsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiReservationResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiReservationResponseError = (postApiReservationResponseDefault) & {
  headers: Headers;
};

export type postApiReservationResponse = (postApiReservationResponseError)

export const getPostApiReservationUrl = () => {




  return `/api/v1/reservations`
}

/**
 * @summary Create a reservation
 */
export const postApiReservation = async (createReservationDto: CreateReservationDto, options?: RequestInit): Promise<postApiReservationResponse> => {

  return useCustomClient<postApiReservationResponse>(getPostApiReservationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReservationDto)
  }
);}





export const getPostApiReservationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiReservation>>, TError,{data: BodyType<CreateReservationDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiReservation>>, TError,{data: BodyType<CreateReservationDto>}, TContext> => {

const mutationKey = ['postApiReservation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiReservation>>, {data: BodyType<CreateReservationDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiReservation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiReservationMutationResult = NonNullable<Awaited<ReturnType<typeof postApiReservation>>>
    export type PostApiReservationMutationBody = BodyType<CreateReservationDto>
    export type PostApiReservationMutationError = ErrorType<unknown>

    /**
 * @summary Create a reservation
 */
export const usePostApiReservation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiReservation>>, TError,{data: BodyType<CreateReservationDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiReservation>>,
        TError,
        {data: BodyType<CreateReservationDto>},
        TContext
      > => {
      return useMutation(getPostApiReservationMutationOptions(options), queryClient);
    }
    export type patchApiApproveReservationResponseDefault = {
  data: unknown
  status: number
}

;
export type patchApiApproveReservationResponseError = (patchApiApproveReservationResponseDefault) & {
  headers: Headers;
};

export type patchApiApproveReservationResponse = (patchApiApproveReservationResponseError)

export const getPatchApiApproveReservationUrl = (id: string,) => {




  return `/api/v1/reservations/${id}/approve`
}

/**
 * @summary Approve a reservation
 */
export const patchApiApproveReservation = async (id: string, options?: RequestInit): Promise<patchApiApproveReservationResponse> => {

  return useCustomClient<patchApiApproveReservationResponse>(getPatchApiApproveReservationUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getPatchApiApproveReservationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiApproveReservation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiApproveReservation>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiApproveReservation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiApproveReservation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiApproveReservation(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiApproveReservationMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiApproveReservation>>>

    export type PatchApiApproveReservationMutationError = ErrorType<unknown>

    /**
 * @summary Approve a reservation
 */
export const usePatchApiApproveReservation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiApproveReservation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiApproveReservation>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPatchApiApproveReservationMutationOptions(options), queryClient);
    }
    export type patchApiRejectReservationResponseDefault = {
  data: unknown
  status: number
}

;
export type patchApiRejectReservationResponseError = (patchApiRejectReservationResponseDefault) & {
  headers: Headers;
};

export type patchApiRejectReservationResponse = (patchApiRejectReservationResponseError)

export const getPatchApiRejectReservationUrl = (id: string,) => {




  return `/api/v1/reservations/${id}/reject`
}

/**
 * @summary Reject a reservation
 */
export const patchApiRejectReservation = async (id: string, options?: RequestInit): Promise<patchApiRejectReservationResponse> => {

  return useCustomClient<patchApiRejectReservationResponse>(getPatchApiRejectReservationUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getPatchApiRejectReservationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiRejectReservation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiRejectReservation>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiRejectReservation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiRejectReservation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiRejectReservation(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiRejectReservationMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiRejectReservation>>>

    export type PatchApiRejectReservationMutationError = ErrorType<unknown>

    /**
 * @summary Reject a reservation
 */
export const usePatchApiRejectReservation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiRejectReservation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiRejectReservation>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPatchApiRejectReservationMutationOptions(options), queryClient);
    }
