/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiFilesParams,
  PostApiFileUploadBody,
  PostApiTempUploadBody
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type postApiFileUploadResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiFileUploadResponseError = (postApiFileUploadResponseDefault) & {
  headers: Headers;
};

export type postApiFileUploadResponse = (postApiFileUploadResponseError)

export const getPostApiFileUploadUrl = () => {




  return `/api/files/upload`
}

/**
 * @summary Upload a single file
 */
export const postApiFileUpload = async (postApiFileUploadBody: PostApiFileUploadBody, options?: RequestInit): Promise<postApiFileUploadResponse> => {
    const formData = new FormData();
formData.append(`file`, postApiFileUploadBody.file);
if(postApiFileUploadBody.ownerType !== undefined) {
 formData.append(`ownerType`, postApiFileUploadBody.ownerType);
 }
if(postApiFileUploadBody.ownerId !== undefined) {
 formData.append(`ownerId`, postApiFileUploadBody.ownerId);
 }
if(postApiFileUploadBody.visibility !== undefined) {
 formData.append(`visibility`, postApiFileUploadBody.visibility);
 }
if(postApiFileUploadBody.isSensitive !== undefined) {
 formData.append(`isSensitive`, postApiFileUploadBody.isSensitive.toString())
 }

  return useCustomClient<postApiFileUploadResponse>(getPostApiFileUploadUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getPostApiFileUploadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFileUpload>>, TError,{data: BodyType<PostApiFileUploadBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiFileUpload>>, TError,{data: BodyType<PostApiFileUploadBody>}, TContext> => {

const mutationKey = ['postApiFileUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiFileUpload>>, {data: BodyType<PostApiFileUploadBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiFileUpload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiFileUploadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiFileUpload>>>
    export type PostApiFileUploadMutationBody = BodyType<PostApiFileUploadBody>
    export type PostApiFileUploadMutationError = ErrorType<unknown>

    /**
 * @summary Upload a single file
 */
export const usePostApiFileUpload = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFileUpload>>, TError,{data: BodyType<PostApiFileUploadBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiFileUpload>>,
        TError,
        {data: BodyType<PostApiFileUploadBody>},
        TContext
      > => {
      return useMutation(getPostApiFileUploadMutationOptions(options), queryClient);
    }
    export type postApiFileUploadMultipleResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiFileUploadMultipleResponseError = (postApiFileUploadMultipleResponseDefault) & {
  headers: Headers;
};

export type postApiFileUploadMultipleResponse = (postApiFileUploadMultipleResponseError)

export const getPostApiFileUploadMultipleUrl = () => {




  return `/api/files/upload-multiple`
}

/**
 * @summary Upload multiple files (max 10)
 */
export const postApiFileUploadMultiple = async ( options?: RequestInit): Promise<postApiFileUploadMultipleResponse> => {

  return useCustomClient<postApiFileUploadMultipleResponse>(getPostApiFileUploadMultipleUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiFileUploadMultipleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFileUploadMultiple>>, TError,void, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiFileUploadMultiple>>, TError,void, TContext> => {

const mutationKey = ['postApiFileUploadMultiple'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiFileUploadMultiple>>, void> = () => {


          return  postApiFileUploadMultiple(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiFileUploadMultipleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiFileUploadMultiple>>>

    export type PostApiFileUploadMultipleMutationError = ErrorType<unknown>

    /**
 * @summary Upload multiple files (max 10)
 */
export const usePostApiFileUploadMultiple = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiFileUploadMultiple>>, TError,void, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiFileUploadMultiple>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiFileUploadMultipleMutationOptions(options), queryClient);
    }
    export type getApiFilesResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiFilesResponseError = (getApiFilesResponseDefault) & {
  headers: Headers;
};

export type getApiFilesResponse = (getApiFilesResponseError)

export const getGetApiFilesUrl = (params?: GetApiFilesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/files?${stringifiedParams}` : `/api/files`
}

/**
 * @summary List files with filters
 */
export const getApiFiles = async (params?: GetApiFilesParams, options?: RequestInit): Promise<getApiFilesResponse> => {

  return useCustomClient<getApiFilesResponse>(getGetApiFilesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiFilesInfiniteQueryKey = (params?: GetApiFilesParams,) => {
    return [
    'infinite', `/api/files`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetApiFilesQueryKey = (params?: GetApiFilesParams,) => {
    return [
    `/api/files`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiFilesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiFiles>>>, TError = ErrorType<unknown>>(params?: GetApiFilesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFilesInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFiles>>> = ({ signal }) => getApiFiles(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFilesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFiles>>>
export type GetApiFilesInfiniteQueryError = ErrorType<unknown>


export function useGetApiFilesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFiles>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiFilesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFiles>>,
          TError,
          Awaited<ReturnType<typeof getApiFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFilesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFiles>>>, TError = ErrorType<unknown>>(
 params?: GetApiFilesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFiles>>,
          TError,
          Awaited<ReturnType<typeof getApiFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFilesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFiles>>>, TError = ErrorType<unknown>>(
 params?: GetApiFilesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List files with filters
 */

export function useGetApiFilesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFiles>>>, TError = ErrorType<unknown>>(
 params?: GetApiFilesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFilesInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List files with filters
 */
export const prefetchGetApiFilesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiFiles>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiFilesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFilesInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiFilesQueryOptions = <TData = Awaited<ReturnType<typeof getApiFiles>>, TError = ErrorType<unknown>>(params?: GetApiFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFilesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFiles>>> = ({ signal }) => getApiFiles(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFilesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFiles>>>
export type GetApiFilesQueryError = ErrorType<unknown>


export function useGetApiFiles<TData = Awaited<ReturnType<typeof getApiFiles>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiFilesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFiles>>,
          TError,
          Awaited<ReturnType<typeof getApiFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFiles<TData = Awaited<ReturnType<typeof getApiFiles>>, TError = ErrorType<unknown>>(
 params?: GetApiFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFiles>>,
          TError,
          Awaited<ReturnType<typeof getApiFiles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFiles<TData = Awaited<ReturnType<typeof getApiFiles>>, TError = ErrorType<unknown>>(
 params?: GetApiFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List files with filters
 */

export function useGetApiFiles<TData = Awaited<ReturnType<typeof getApiFiles>>, TError = ErrorType<unknown>>(
 params?: GetApiFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFilesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List files with filters
 */
export const prefetchGetApiFilesQuery = async <TData = Awaited<ReturnType<typeof getApiFiles>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiFilesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFiles>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFilesQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type getApiFileIdResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiFileIdResponseError = (getApiFileIdResponseDefault) & {
  headers: Headers;
};

export type getApiFileIdResponse = (getApiFileIdResponseError)

export const getGetApiFileIdUrl = (id: string,) => {




  return `/api/files/${id}`
}

/**
 * @summary Get file metadata
 */
export const getApiFileId = async (id: string, options?: RequestInit): Promise<getApiFileIdResponse> => {

  return useCustomClient<getApiFileIdResponse>(getGetApiFileIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiFileIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/files/${id}`
    ] as const;
    }

export const getGetApiFileIdQueryKey = (id: string,) => {
    return [
    `/api/files/${id}`
    ] as const;
    }


export const getGetApiFileIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiFileId>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFileIdInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFileId>>> = ({ signal }) => getApiFileId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFileIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFileId>>>
export type GetApiFileIdInfiniteQueryError = ErrorType<unknown>


export function useGetApiFileIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFileId>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFileId>>,
          TError,
          Awaited<ReturnType<typeof getApiFileId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFileIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFileId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFileId>>,
          TError,
          Awaited<ReturnType<typeof getApiFileId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFileIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFileId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get file metadata
 */

export function useGetApiFileIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFileId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFileIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get file metadata
 */
export const prefetchGetApiFileIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiFileId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFileIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiFileIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiFileId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFileIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFileId>>> = ({ signal }) => getApiFileId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFileIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFileId>>>
export type GetApiFileIdQueryError = ErrorType<unknown>


export function useGetApiFileId<TData = Awaited<ReturnType<typeof getApiFileId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFileId>>,
          TError,
          Awaited<ReturnType<typeof getApiFileId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFileId<TData = Awaited<ReturnType<typeof getApiFileId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFileId>>,
          TError,
          Awaited<ReturnType<typeof getApiFileId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFileId<TData = Awaited<ReturnType<typeof getApiFileId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get file metadata
 */

export function useGetApiFileId<TData = Awaited<ReturnType<typeof getApiFileId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFileIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get file metadata
 */
export const prefetchGetApiFileIdQuery = async <TData = Awaited<ReturnType<typeof getApiFileId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFileIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type deleteApiFileResponseDefault = {
  data: unknown
  status: number
}

;
export type deleteApiFileResponseError = (deleteApiFileResponseDefault) & {
  headers: Headers;
};

export type deleteApiFileResponse = (deleteApiFileResponseError)

export const getDeleteApiFileUrl = (id: string,) => {




  return `/api/files/${id}`
}

/**
 * @summary Soft delete a file
 */
export const deleteApiFile = async (id: string, options?: RequestInit): Promise<deleteApiFileResponse> => {

  return useCustomClient<deleteApiFileResponse>(getDeleteApiFileUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiFileMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiFile>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiFile>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiFile>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiFile(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiFileMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiFile>>>

    export type DeleteApiFileMutationError = ErrorType<unknown>

    /**
 * @summary Soft delete a file
 */
export const useDeleteApiFile = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiFile>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiFile>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiFileMutationOptions(options), queryClient);
    }
    export type getApiFileDownloadUrlResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiFileDownloadUrlResponseError = (getApiFileDownloadUrlResponseDefault) & {
  headers: Headers;
};

export type getApiFileDownloadUrlResponse = (getApiFileDownloadUrlResponseError)

export const getGetApiFileDownloadUrlUrl = (id: string,) => {




  return `/api/files/${id}/download`
}

/**
 * @summary Get presigned download URL
 */
export const getApiFileDownloadUrl = async (id: string, options?: RequestInit): Promise<getApiFileDownloadUrlResponse> => {

  return useCustomClient<getApiFileDownloadUrlResponse>(getGetApiFileDownloadUrlUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiFileDownloadUrlInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/files/${id}/download`
    ] as const;
    }

export const getGetApiFileDownloadUrlQueryKey = (id: string,) => {
    return [
    `/api/files/${id}/download`
    ] as const;
    }


export const getGetApiFileDownloadUrlInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiFileDownloadUrl>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFileDownloadUrlInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFileDownloadUrl>>> = ({ signal }) => getApiFileDownloadUrl(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFileDownloadUrlInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFileDownloadUrl>>>
export type GetApiFileDownloadUrlInfiniteQueryError = ErrorType<unknown>


export function useGetApiFileDownloadUrlInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFileDownloadUrl>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFileDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof getApiFileDownloadUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFileDownloadUrlInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFileDownloadUrl>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFileDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof getApiFileDownloadUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFileDownloadUrlInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFileDownloadUrl>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get presigned download URL
 */

export function useGetApiFileDownloadUrlInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiFileDownloadUrl>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFileDownloadUrlInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get presigned download URL
 */
export const prefetchGetApiFileDownloadUrlInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFileDownloadUrlInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiFileDownloadUrlQueryOptions = <TData = Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFileDownloadUrlQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFileDownloadUrl>>> = ({ signal }) => getApiFileDownloadUrl(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiFileDownloadUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFileDownloadUrl>>>
export type GetApiFileDownloadUrlQueryError = ErrorType<unknown>


export function useGetApiFileDownloadUrl<TData = Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFileDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof getApiFileDownloadUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFileDownloadUrl<TData = Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFileDownloadUrl>>,
          TError,
          Awaited<ReturnType<typeof getApiFileDownloadUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiFileDownloadUrl<TData = Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get presigned download URL
 */

export function useGetApiFileDownloadUrl<TData = Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiFileDownloadUrlQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get presigned download URL
 */
export const prefetchGetApiFileDownloadUrlQuery = async <TData = Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFileDownloadUrl>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiFileDownloadUrlQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type patchApiFileVisibilityResponseDefault = {
  data: unknown
  status: number
}

;
export type patchApiFileVisibilityResponseError = (patchApiFileVisibilityResponseDefault) & {
  headers: Headers;
};

export type patchApiFileVisibilityResponse = (patchApiFileVisibilityResponseError)

export const getPatchApiFileVisibilityUrl = (id: string,) => {




  return `/api/files/${id}/visibility`
}

/**
 * @summary Update file visibility
 */
export const patchApiFileVisibility = async (id: string, options?: RequestInit): Promise<patchApiFileVisibilityResponse> => {

  return useCustomClient<patchApiFileVisibilityResponse>(getPatchApiFileVisibilityUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getPatchApiFileVisibilityMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiFileVisibility>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiFileVisibility>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiFileVisibility'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiFileVisibility>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiFileVisibility(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiFileVisibilityMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiFileVisibility>>>

    export type PatchApiFileVisibilityMutationError = ErrorType<unknown>

    /**
 * @summary Update file visibility
 */
export const usePatchApiFileVisibility = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiFileVisibility>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiFileVisibility>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPatchApiFileVisibilityMutationOptions(options), queryClient);
    }
    export type postApiTempUploadResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiTempUploadResponseError = (postApiTempUploadResponseDefault) & {
  headers: Headers;
};

export type postApiTempUploadResponse = (postApiTempUploadResponseError)

export const getPostApiTempUploadUrl = () => {




  return `/api/files/temp-upload`
}

/**
 * @summary Upload file to temp staging (2-phase upload step 1)
 */
export const postApiTempUpload = async (postApiTempUploadBody: PostApiTempUploadBody, options?: RequestInit): Promise<postApiTempUploadResponse> => {
    const formData = new FormData();
formData.append(`file`, postApiTempUploadBody.file);

  return useCustomClient<postApiTempUploadResponse>(getPostApiTempUploadUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}





export const getPostApiTempUploadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTempUpload>>, TError,{data: BodyType<PostApiTempUploadBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiTempUpload>>, TError,{data: BodyType<PostApiTempUploadBody>}, TContext> => {

const mutationKey = ['postApiTempUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTempUpload>>, {data: BodyType<PostApiTempUploadBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiTempUpload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiTempUploadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTempUpload>>>
    export type PostApiTempUploadMutationBody = BodyType<PostApiTempUploadBody>
    export type PostApiTempUploadMutationError = ErrorType<unknown>

    /**
 * @summary Upload file to temp staging (2-phase upload step 1)
 */
export const usePostApiTempUpload = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTempUpload>>, TError,{data: BodyType<PostApiTempUploadBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTempUpload>>,
        TError,
        {data: BodyType<PostApiTempUploadBody>},
        TContext
      > => {
      return useMutation(getPostApiTempUploadMutationOptions(options), queryClient);
    }
    export type postApiConfirmUploadResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiConfirmUploadResponseError = (postApiConfirmUploadResponseDefault) & {
  headers: Headers;
};

export type postApiConfirmUploadResponse = (postApiConfirmUploadResponseError)

export const getPostApiConfirmUploadUrl = (id: string,) => {




  return `/api/files/${id}/confirm`
}

/**
 * @summary Confirm temp upload and move to final location (2-phase upload step 2)
 */
export const postApiConfirmUpload = async (id: string, options?: RequestInit): Promise<postApiConfirmUploadResponse> => {

  return useCustomClient<postApiConfirmUploadResponse>(getPostApiConfirmUploadUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiConfirmUploadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiConfirmUpload>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiConfirmUpload>>, TError,{id: string}, TContext> => {

const mutationKey = ['postApiConfirmUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiConfirmUpload>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postApiConfirmUpload(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiConfirmUploadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiConfirmUpload>>>

    export type PostApiConfirmUploadMutationError = ErrorType<unknown>

    /**
 * @summary Confirm temp upload and move to final location (2-phase upload step 2)
 */
export const usePostApiConfirmUpload = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiConfirmUpload>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiConfirmUpload>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostApiConfirmUploadMutationOptions(options), queryClient);
    }
    export type deleteApiAbortUploadResponseDefault = {
  data: unknown
  status: number
}

;
export type deleteApiAbortUploadResponseError = (deleteApiAbortUploadResponseDefault) & {
  headers: Headers;
};

export type deleteApiAbortUploadResponse = (deleteApiAbortUploadResponseError)

export const getDeleteApiAbortUploadUrl = (id: string,) => {




  return `/api/files/${id}/abort`
}

/**
 * @summary Abort temp upload and clean up (2-phase upload cancel)
 */
export const deleteApiAbortUpload = async (id: string, options?: RequestInit): Promise<deleteApiAbortUploadResponse> => {

  return useCustomClient<deleteApiAbortUploadResponse>(getDeleteApiAbortUploadUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiAbortUploadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAbortUpload>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAbortUpload>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiAbortUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAbortUpload>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiAbortUpload(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAbortUploadMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAbortUpload>>>

    export type DeleteApiAbortUploadMutationError = ErrorType<unknown>

    /**
 * @summary Abort temp upload and clean up (2-phase upload cancel)
 */
export const useDeleteApiAbortUpload = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAbortUpload>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAbortUpload>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiAbortUploadMutationOptions(options), queryClient);
    }
