/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateLeadActivityDto,
  CreateLeadDto,
  GetApiLeadsParams,
  UpdateLeadDto
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiLeadsResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiLeadsResponseError = (getApiLeadsResponseDefault) & {
  headers: Headers;
};

export type getApiLeadsResponse = (getApiLeadsResponseError)

export const getGetApiLeadsUrl = (params?: GetApiLeadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/leads?${stringifiedParams}` : `/api/leads`
}

/**
 * @summary List leads with filters
 */
export const getApiLeads = async (params?: GetApiLeadsParams, options?: RequestInit): Promise<getApiLeadsResponse> => {

  return useCustomClient<getApiLeadsResponse>(getGetApiLeadsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiLeadsInfiniteQueryKey = (params?: GetApiLeadsParams,) => {
    return [
    'infinite', `/api/leads`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetApiLeadsQueryKey = (params?: GetApiLeadsParams,) => {
    return [
    `/api/leads`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiLeadsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = ErrorType<unknown>>(params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadsInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeads>>> = ({ signal }) => getApiLeads(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeads>>>
export type GetApiLeadsInfiniteQueryError = ErrorType<unknown>


export function useGetApiLeadsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiLeadsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeads>>,
          TError,
          Awaited<ReturnType<typeof getApiLeads>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = ErrorType<unknown>>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeads>>,
          TError,
          Awaited<ReturnType<typeof getApiLeads>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = ErrorType<unknown>>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List leads with filters
 */

export function useGetApiLeadsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeads>>>, TError = ErrorType<unknown>>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List leads with filters
 */
export const prefetchGetApiLeadsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeads>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiLeadsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiLeadsQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeads>>, TError = ErrorType<unknown>>(params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeads>>> = ({ signal }) => getApiLeads(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeads>>>
export type GetApiLeadsQueryError = ErrorType<unknown>


export function useGetApiLeads<TData = Awaited<ReturnType<typeof getApiLeads>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiLeadsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeads>>,
          TError,
          Awaited<ReturnType<typeof getApiLeads>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeads<TData = Awaited<ReturnType<typeof getApiLeads>>, TError = ErrorType<unknown>>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeads>>,
          TError,
          Awaited<ReturnType<typeof getApiLeads>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeads<TData = Awaited<ReturnType<typeof getApiLeads>>, TError = ErrorType<unknown>>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List leads with filters
 */

export function useGetApiLeads<TData = Awaited<ReturnType<typeof getApiLeads>>, TError = ErrorType<unknown>>(
 params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List leads with filters
 */
export const prefetchGetApiLeadsQuery = async <TData = Awaited<ReturnType<typeof getApiLeads>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiLeadsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeads>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiLeadResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiLeadResponseError = (postApiLeadResponseDefault) & {
  headers: Headers;
};

export type postApiLeadResponse = (postApiLeadResponseError)

export const getPostApiLeadUrl = () => {




  return `/api/leads`
}

/**
 * @summary Create a lead
 */
export const postApiLead = async (createLeadDto: CreateLeadDto, options?: RequestInit): Promise<postApiLeadResponse> => {

  return useCustomClient<postApiLeadResponse>(getPostApiLeadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLeadDto)
  }
);}





export const getPostApiLeadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLead>>, TError,{data: BodyType<CreateLeadDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiLead>>, TError,{data: BodyType<CreateLeadDto>}, TContext> => {

const mutationKey = ['postApiLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLead>>, {data: BodyType<CreateLeadDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiLead(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiLeadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLead>>>
    export type PostApiLeadMutationBody = BodyType<CreateLeadDto>
    export type PostApiLeadMutationError = ErrorType<unknown>

    /**
 * @summary Create a lead
 */
export const usePostApiLead = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLead>>, TError,{data: BodyType<CreateLeadDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLead>>,
        TError,
        {data: BodyType<CreateLeadDto>},
        TContext
      > => {
      return useMutation(getPostApiLeadMutationOptions(options), queryClient);
    }
    export type getApiLeadIdResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiLeadIdResponseError = (getApiLeadIdResponseDefault) & {
  headers: Headers;
};

export type getApiLeadIdResponse = (getApiLeadIdResponseError)

export const getGetApiLeadIdUrl = (id: string,) => {




  return `/api/leads/${id}`
}

/**
 * @summary Get lead by ID
 */
export const getApiLeadId = async (id: string, options?: RequestInit): Promise<getApiLeadIdResponse> => {

  return useCustomClient<getApiLeadIdResponse>(getGetApiLeadIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiLeadIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/leads/${id}`
    ] as const;
    }

export const getGetApiLeadIdQueryKey = (id: string,) => {
    return [
    `/api/leads/${id}`
    ] as const;
    }


export const getGetApiLeadIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadIdInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadId>>> = ({ signal }) => getApiLeadId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadId>>>
export type GetApiLeadIdInfiniteQueryError = ErrorType<unknown>


export function useGetApiLeadIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadId>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadId>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get lead by ID
 */

export function useGetApiLeadIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get lead by ID
 */
export const prefetchGetApiLeadIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiLeadIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadId>>> = ({ signal }) => getApiLeadId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadId>>>
export type GetApiLeadIdQueryError = ErrorType<unknown>


export function useGetApiLeadId<TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadId>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadId<TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadId>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadId<TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get lead by ID
 */

export function useGetApiLeadId<TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get lead by ID
 */
export const prefetchGetApiLeadIdQuery = async <TData = Awaited<ReturnType<typeof getApiLeadId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type patchApiLeadResponseDefault = {
  data: unknown
  status: number
}

;
export type patchApiLeadResponseError = (patchApiLeadResponseDefault) & {
  headers: Headers;
};

export type patchApiLeadResponse = (patchApiLeadResponseError)

export const getPatchApiLeadUrl = (id: string,) => {




  return `/api/leads/${id}`
}

/**
 * @summary Update a lead
 */
export const patchApiLead = async (id: string,
    updateLeadDto: UpdateLeadDto, options?: RequestInit): Promise<patchApiLeadResponse> => {

  return useCustomClient<patchApiLeadResponse>(getPatchApiLeadUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateLeadDto)
  }
);}





export const getPatchApiLeadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiLead>>, TError,{id: string;data: BodyType<UpdateLeadDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiLead>>, TError,{id: string;data: BodyType<UpdateLeadDto>}, TContext> => {

const mutationKey = ['patchApiLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiLead>>, {id: string;data: BodyType<UpdateLeadDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiLead(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiLeadMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiLead>>>
    export type PatchApiLeadMutationBody = BodyType<UpdateLeadDto>
    export type PatchApiLeadMutationError = ErrorType<unknown>

    /**
 * @summary Update a lead
 */
export const usePatchApiLead = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiLead>>, TError,{id: string;data: BodyType<UpdateLeadDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiLead>>,
        TError,
        {id: string;data: BodyType<UpdateLeadDto>},
        TContext
      > => {
      return useMutation(getPatchApiLeadMutationOptions(options), queryClient);
    }
    export type deleteApiLeadResponseDefault = {
  data: unknown
  status: number
}

;
export type deleteApiLeadResponseError = (deleteApiLeadResponseDefault) & {
  headers: Headers;
};

export type deleteApiLeadResponse = (deleteApiLeadResponseError)

export const getDeleteApiLeadUrl = (id: string,) => {




  return `/api/leads/${id}`
}

/**
 * @summary Soft delete a lead
 */
export const deleteApiLead = async (id: string, options?: RequestInit): Promise<deleteApiLeadResponse> => {

  return useCustomClient<deleteApiLeadResponse>(getDeleteApiLeadUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiLeadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiLead>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiLead>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiLead>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiLead(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiLeadMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiLead>>>

    export type DeleteApiLeadMutationError = ErrorType<unknown>

    /**
 * @summary Soft delete a lead
 */
export const useDeleteApiLead = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiLead>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiLead>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiLeadMutationOptions(options), queryClient);
    }
    export type getApiLeadActivitiesResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiLeadActivitiesResponseError = (getApiLeadActivitiesResponseDefault) & {
  headers: Headers;
};

export type getApiLeadActivitiesResponse = (getApiLeadActivitiesResponseError)

export const getGetApiLeadActivitiesUrl = (id: string,) => {




  return `/api/leads/${id}/activities`
}

/**
 * @summary List activities for a lead
 */
export const getApiLeadActivities = async (id: string, options?: RequestInit): Promise<getApiLeadActivitiesResponse> => {

  return useCustomClient<getApiLeadActivitiesResponse>(getGetApiLeadActivitiesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiLeadActivitiesInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/leads/${id}/activities`
    ] as const;
    }

export const getGetApiLeadActivitiesQueryKey = (id: string,) => {
    return [
    `/api/leads/${id}/activities`
    ] as const;
    }


export const getGetApiLeadActivitiesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadActivitiesInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadActivities>>> = ({ signal }) => getApiLeadActivities(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadActivitiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadActivities>>>
export type GetApiLeadActivitiesInfiniteQueryError = ErrorType<unknown>


export function useGetApiLeadActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadActivities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadActivities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List activities for a lead
 */

export function useGetApiLeadActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiLeadActivities>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadActivitiesInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List activities for a lead
 */
export const prefetchGetApiLeadActivitiesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadActivitiesInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiLeadActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiLeadActivitiesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLeadActivities>>> = ({ signal }) => getApiLeadActivities(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiLeadActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiLeadActivities>>>
export type GetApiLeadActivitiesQueryError = ErrorType<unknown>


export function useGetApiLeadActivities<TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadActivities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadActivities<TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLeadActivities>>,
          TError,
          Awaited<ReturnType<typeof getApiLeadActivities>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiLeadActivities<TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List activities for a lead
 */

export function useGetApiLeadActivities<TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiLeadActivitiesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List activities for a lead
 */
export const prefetchGetApiLeadActivitiesQuery = async <TData = Awaited<ReturnType<typeof getApiLeadActivities>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiLeadActivities>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiLeadActivitiesQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiLeadActivityResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiLeadActivityResponseError = (postApiLeadActivityResponseDefault) & {
  headers: Headers;
};

export type postApiLeadActivityResponse = (postApiLeadActivityResponseError)

export const getPostApiLeadActivityUrl = (id: string,) => {




  return `/api/leads/${id}/activities`
}

/**
 * @summary Add an activity to a lead
 */
export const postApiLeadActivity = async (id: string,
    createLeadActivityDto: CreateLeadActivityDto, options?: RequestInit): Promise<postApiLeadActivityResponse> => {

  return useCustomClient<postApiLeadActivityResponse>(getPostApiLeadActivityUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLeadActivityDto)
  }
);}





export const getPostApiLeadActivityMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadActivity>>, TError,{id: string;data: BodyType<CreateLeadActivityDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiLeadActivity>>, TError,{id: string;data: BodyType<CreateLeadActivityDto>}, TContext> => {

const mutationKey = ['postApiLeadActivity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiLeadActivity>>, {id: string;data: BodyType<CreateLeadActivityDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiLeadActivity(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiLeadActivityMutationResult = NonNullable<Awaited<ReturnType<typeof postApiLeadActivity>>>
    export type PostApiLeadActivityMutationBody = BodyType<CreateLeadActivityDto>
    export type PostApiLeadActivityMutationError = ErrorType<unknown>

    /**
 * @summary Add an activity to a lead
 */
export const usePostApiLeadActivity = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiLeadActivity>>, TError,{id: string;data: BodyType<CreateLeadActivityDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiLeadActivity>>,
        TError,
        {id: string;data: BodyType<CreateLeadActivityDto>},
        TContext
      > => {
      return useMutation(getPostApiLeadActivityMutationOptions(options), queryClient);
    }
