/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePropertyDto
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiPropertiesResponse200 = {
  data: void
  status: 200
}

export type getApiPropertiesResponseSuccess = (getApiPropertiesResponse200) & {
  headers: Headers;
};
;

export type getApiPropertiesResponse = (getApiPropertiesResponseSuccess)

export const getGetApiPropertiesUrl = () => {




  return `/api/v1/properties`
}

/**
 * @summary List properties with filters
 */
export const getApiProperties = async ( options?: RequestInit): Promise<getApiPropertiesResponse> => {

  return useCustomClient<getApiPropertiesResponse>(getGetApiPropertiesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPropertiesInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/properties`
    ] as const;
    }

export const getGetApiPropertiesQueryKey = () => {
    return [
    `/api/v1/properties`
    ] as const;
    }


export const getGetApiPropertiesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProperties>>> = ({ signal }) => getApiProperties({ signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProperties>>>
export type GetApiPropertiesInfiniteQueryError = ErrorType<unknown>


export function useGetApiPropertiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProperties>>,
          TError,
          Awaited<ReturnType<typeof getApiProperties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProperties>>,
          TError,
          Awaited<ReturnType<typeof getApiProperties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List properties with filters
 */

export function useGetApiPropertiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List properties with filters
 */
export const prefetchGetApiPropertiesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiProperties>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiPropertiesQueryOptions = <TData = Awaited<ReturnType<typeof getApiProperties>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProperties>>> = ({ signal }) => getApiProperties({ signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProperties>>>
export type GetApiPropertiesQueryError = ErrorType<unknown>


export function useGetApiProperties<TData = Awaited<ReturnType<typeof getApiProperties>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProperties>>,
          TError,
          Awaited<ReturnType<typeof getApiProperties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProperties<TData = Awaited<ReturnType<typeof getApiProperties>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProperties>>,
          TError,
          Awaited<ReturnType<typeof getApiProperties>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProperties<TData = Awaited<ReturnType<typeof getApiProperties>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List properties with filters
 */

export function useGetApiProperties<TData = Awaited<ReturnType<typeof getApiProperties>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List properties with filters
 */
export const prefetchGetApiPropertiesQuery = async <TData = Awaited<ReturnType<typeof getApiProperties>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiPropertyResponse201 = {
  data: void
  status: 201
}

export type postApiPropertyResponseSuccess = (postApiPropertyResponse201) & {
  headers: Headers;
};
;

export type postApiPropertyResponse = (postApiPropertyResponseSuccess)

export const getPostApiPropertyUrl = () => {




  return `/api/v1/properties`
}

/**
 * @summary Create a new property
 */
export const postApiProperty = async (createPropertyDto: CreatePropertyDto, options?: RequestInit): Promise<postApiPropertyResponse> => {

  return useCustomClient<postApiPropertyResponse>(getPostApiPropertyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPropertyDto)
  }
);}





export const getPostApiPropertyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProperty>>, TError,{data: BodyType<CreatePropertyDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiProperty>>, TError,{data: BodyType<CreatePropertyDto>}, TContext> => {

const mutationKey = ['postApiProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProperty>>, {data: BodyType<CreatePropertyDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiProperty(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProperty>>>
    export type PostApiPropertyMutationBody = BodyType<CreatePropertyDto>
    export type PostApiPropertyMutationError = ErrorType<unknown>

    /**
 * @summary Create a new property
 */
export const usePostApiProperty = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProperty>>, TError,{data: BodyType<CreatePropertyDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiProperty>>,
        TError,
        {data: BodyType<CreatePropertyDto>},
        TContext
      > => {
      return useMutation(getPostApiPropertyMutationOptions(options), queryClient);
    }
    export type getApiPropertyTypesResponse200 = {
  data: void
  status: 200
}

export type getApiPropertyTypesResponseSuccess = (getApiPropertyTypesResponse200) & {
  headers: Headers;
};
;

export type getApiPropertyTypesResponse = (getApiPropertyTypesResponseSuccess)

export const getGetApiPropertyTypesUrl = () => {




  return `/api/v1/properties/types`
}

/**
 * @summary List property types
 */
export const getApiPropertyTypes = async ( options?: RequestInit): Promise<getApiPropertyTypesResponse> => {

  return useCustomClient<getApiPropertyTypesResponse>(getGetApiPropertyTypesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPropertyTypesInfiniteQueryKey = () => {
    return [
    'infinite', `/api/v1/properties/types`
    ] as const;
    }

export const getGetApiPropertyTypesQueryKey = () => {
    return [
    `/api/v1/properties/types`
    ] as const;
    }


export const getGetApiPropertyTypesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyTypesInfiniteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyTypes>>> = ({ signal }) => getApiPropertyTypes({ signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyTypesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyTypes>>>
export type GetApiPropertyTypesInfiniteQueryError = ErrorType<unknown>


export function useGetApiPropertyTypesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyTypesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyTypesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List property types
 */

export function useGetApiPropertyTypesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyTypesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List property types
 */
export const prefetchGetApiPropertyTypesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyTypesInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiPropertyTypesQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyTypes>>> = ({ signal }) => getApiPropertyTypes({ signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyTypes>>>
export type GetApiPropertyTypesQueryError = ErrorType<unknown>


export function useGetApiPropertyTypes<TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyTypes<TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyTypes<TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List property types
 */

export function useGetApiPropertyTypes<TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List property types
 */
export const prefetchGetApiPropertyTypesQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyTypesQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiPropertyTypeResponse201 = {
  data: void
  status: 201
}

export type postApiPropertyTypeResponseSuccess = (postApiPropertyTypeResponse201) & {
  headers: Headers;
};
;

export type postApiPropertyTypeResponse = (postApiPropertyTypeResponseSuccess)

export const getPostApiPropertyTypeUrl = () => {




  return `/api/v1/properties/types`
}

/**
 * @summary Create a property type
 */
export const postApiPropertyType = async ( options?: RequestInit): Promise<postApiPropertyTypeResponse> => {

  return useCustomClient<postApiPropertyTypeResponse>(getPostApiPropertyTypeUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiPropertyTypeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyType>>, TError,void, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyType>>, TError,void, TContext> => {

const mutationKey = ['postApiPropertyType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPropertyType>>, void> = () => {


          return  postApiPropertyType(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPropertyTypeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPropertyType>>>

    export type PostApiPropertyTypeMutationError = ErrorType<unknown>

    /**
 * @summary Create a property type
 */
export const usePostApiPropertyType = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyType>>, TError,void, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPropertyType>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiPropertyTypeMutationOptions(options), queryClient);
    }
    export type getApiPropertyIdResponse200 = {
  data: void
  status: 200
}

export type getApiPropertyIdResponseSuccess = (getApiPropertyIdResponse200) & {
  headers: Headers;
};
;

export type getApiPropertyIdResponse = (getApiPropertyIdResponseSuccess)

export const getGetApiPropertyIdUrl = (id: string,) => {




  return `/api/v1/properties/${id}`
}

/**
 * @summary Get property by ID
 */
export const getApiPropertyId = async (id: string, options?: RequestInit): Promise<getApiPropertyIdResponse> => {

  return useCustomClient<getApiPropertyIdResponse>(getGetApiPropertyIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPropertyIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/v1/properties/${id}`
    ] as const;
    }

export const getGetApiPropertyIdQueryKey = (id: string,) => {
    return [
    `/api/v1/properties/${id}`
    ] as const;
    }


export const getGetApiPropertyIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyIdInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyId>>> = ({ signal }) => getApiPropertyId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyId>>>
export type GetApiPropertyIdInfiniteQueryError = ErrorType<unknown>


export function useGetApiPropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get property by ID
 */

export function useGetApiPropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get property by ID
 */
export const prefetchGetApiPropertyIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiPropertyIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyId>>> = ({ signal }) => getApiPropertyId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyId>>>
export type GetApiPropertyIdQueryError = ErrorType<unknown>


export function useGetApiPropertyId<TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyId<TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyId<TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get property by ID
 */

export function useGetApiPropertyId<TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get property by ID
 */
export const prefetchGetApiPropertyIdQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type patchApiPropertyResponse200 = {
  data: void
  status: 200
}

export type patchApiPropertyResponseSuccess = (patchApiPropertyResponse200) & {
  headers: Headers;
};
;

export type patchApiPropertyResponse = (patchApiPropertyResponseSuccess)

export const getPatchApiPropertyUrl = (id: string,) => {




  return `/api/v1/properties/${id}`
}

/**
 * @summary Update a property
 */
export const patchApiProperty = async (id: string, options?: RequestInit): Promise<patchApiPropertyResponse> => {

  return useCustomClient<patchApiPropertyResponse>(getPatchApiPropertyUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}





export const getPatchApiPropertyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProperty>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiProperty>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiProperty>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiProperty(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiProperty>>>

    export type PatchApiPropertyMutationError = ErrorType<unknown>

    /**
 * @summary Update a property
 */
export const usePatchApiProperty = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProperty>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiProperty>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPatchApiPropertyMutationOptions(options), queryClient);
    }
    export type deleteApiPropertyResponse200 = {
  data: void
  status: 200
}

export type deleteApiPropertyResponseSuccess = (deleteApiPropertyResponse200) & {
  headers: Headers;
};
;

export type deleteApiPropertyResponse = (deleteApiPropertyResponseSuccess)

export const getDeleteApiPropertyUrl = (id: string,) => {




  return `/api/v1/properties/${id}`
}

/**
 * @summary Soft delete a property
 */
export const deleteApiProperty = async (id: string, options?: RequestInit): Promise<deleteApiPropertyResponse> => {

  return useCustomClient<deleteApiPropertyResponse>(getDeleteApiPropertyUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiPropertyMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProperty>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiProperty>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiProperty>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiProperty(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiProperty>>>

    export type DeleteApiPropertyMutationError = ErrorType<unknown>

    /**
 * @summary Soft delete a property
 */
export const useDeleteApiProperty = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProperty>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiProperty>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiPropertyMutationOptions(options), queryClient);
    }
