/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePropertyDto,
  CreatePropertyMediaDto,
  CreatePropertyTypeDto,
  GetApiPropertiesAdminParams,
  GetApiPropertiesAvailableForAssignmentParams,
  GetApiPropertiesParams,
  ReorderPropertyMediaDto,
  UpdatePropertyDto,
  UpdatePropertyMediaDto
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary List public properties with filters
 */
export const getApiProperties = (
    params?: GetApiPropertiesParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiPropertiesInfiniteQueryKey = (params?: GetApiPropertiesParams,) => {
    return [
    'infinite', `/api/properties`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiPropertiesQueryKey = (params?: GetApiPropertiesParams,) => {
    return [
    `/api/properties`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiPropertiesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = unknown>(params?: GetApiPropertiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProperties>>> = ({ signal }) => getApiProperties(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProperties>>>
export type GetApiPropertiesInfiniteQueryError = unknown


export function useGetApiPropertiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = unknown>(
 params: undefined |  GetApiPropertiesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProperties>>,
          TError,
          Awaited<ReturnType<typeof getApiProperties>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = unknown>(
 params?: GetApiPropertiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProperties>>,
          TError,
          Awaited<ReturnType<typeof getApiProperties>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = unknown>(
 params?: GetApiPropertiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List public properties with filters
 */

export function useGetApiPropertiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiProperties>>>, TError = unknown>(
 params?: GetApiPropertiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List public properties with filters
 */
export const prefetchGetApiPropertiesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiProperties>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiPropertiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiPropertiesQueryOptions = <TData = Awaited<ReturnType<typeof getApiProperties>>, TError = unknown>(params?: GetApiPropertiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProperties>>> = ({ signal }) => getApiProperties(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiProperties>>>
export type GetApiPropertiesQueryError = unknown


export function useGetApiProperties<TData = Awaited<ReturnType<typeof getApiProperties>>, TError = unknown>(
 params: undefined |  GetApiPropertiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProperties>>,
          TError,
          Awaited<ReturnType<typeof getApiProperties>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProperties<TData = Awaited<ReturnType<typeof getApiProperties>>, TError = unknown>(
 params?: GetApiPropertiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProperties>>,
          TError,
          Awaited<ReturnType<typeof getApiProperties>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiProperties<TData = Awaited<ReturnType<typeof getApiProperties>>, TError = unknown>(
 params?: GetApiPropertiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List public properties with filters
 */

export function useGetApiProperties<TData = Awaited<ReturnType<typeof getApiProperties>>, TError = unknown>(
 params?: GetApiPropertiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List public properties with filters
 */
export const prefetchGetApiPropertiesQuery = async <TData = Awaited<ReturnType<typeof getApiProperties>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiPropertiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiProperties>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a new property
 */
export const postApiProperty = (
    createPropertyDto: CreatePropertyDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPropertyDto, signal
    },
      );
    }
  


export const getPostApiPropertyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProperty>>, TError,{data: CreatePropertyDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiProperty>>, TError,{data: CreatePropertyDto}, TContext> => {

const mutationKey = ['postApiProperty'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiProperty>>, {data: CreatePropertyDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiProperty(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiProperty>>>
    export type PostApiPropertyMutationBody = CreatePropertyDto
    export type PostApiPropertyMutationError = unknown

    /**
 * @summary Create a new property
 */
export const usePostApiProperty = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiProperty>>, TError,{data: CreatePropertyDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiProperty>>,
        TError,
        {data: CreatePropertyDto},
        TContext
      > => {

      const mutationOptions = getPostApiPropertyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List properties available for sales to claim assignment
 */
export const getApiPropertiesAvailableForAssignment = (
    params?: GetApiPropertiesAvailableForAssignmentParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/available-for-assignment`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiPropertiesAvailableForAssignmentInfiniteQueryKey = (params?: GetApiPropertiesAvailableForAssignmentParams,) => {
    return [
    'infinite', `/api/properties/available-for-assignment`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiPropertiesAvailableForAssignmentQueryKey = (params?: GetApiPropertiesAvailableForAssignmentParams,) => {
    return [
    `/api/properties/available-for-assignment`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiPropertiesAvailableForAssignmentInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>>, TError = unknown>(params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesAvailableForAssignmentInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>> = ({ signal }) => getApiPropertiesAvailableForAssignment(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesAvailableForAssignmentInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>>
export type GetApiPropertiesAvailableForAssignmentInfiniteQueryError = unknown


export function useGetApiPropertiesAvailableForAssignmentInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>>, TError = unknown>(
 params: undefined |  GetApiPropertiesAvailableForAssignmentParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesAvailableForAssignmentInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>>, TError = unknown>(
 params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesAvailableForAssignmentInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>>, TError = unknown>(
 params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List properties available for sales to claim assignment
 */

export function useGetApiPropertiesAvailableForAssignmentInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>>, TError = unknown>(
 params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesAvailableForAssignmentInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List properties available for sales to claim assignment
 */
export const prefetchGetApiPropertiesAvailableForAssignmentInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesAvailableForAssignmentInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiPropertiesAvailableForAssignmentQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError = unknown>(params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesAvailableForAssignmentQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>> = ({ signal }) => getApiPropertiesAvailableForAssignment(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesAvailableForAssignmentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>>
export type GetApiPropertiesAvailableForAssignmentQueryError = unknown


export function useGetApiPropertiesAvailableForAssignment<TData = Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError = unknown>(
 params: undefined |  GetApiPropertiesAvailableForAssignmentParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesAvailableForAssignment<TData = Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError = unknown>(
 params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesAvailableForAssignment<TData = Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError = unknown>(
 params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List properties available for sales to claim assignment
 */

export function useGetApiPropertiesAvailableForAssignment<TData = Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError = unknown>(
 params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesAvailableForAssignmentQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List properties available for sales to claim assignment
 */
export const prefetchGetApiPropertiesAvailableForAssignmentQuery = async <TData = Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiPropertiesAvailableForAssignmentParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAvailableForAssignment>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesAvailableForAssignmentQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary List all properties for admin management
 */
export const getApiPropertiesAdmin = (
    params?: GetApiPropertiesAdminParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/properties/admin`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiPropertiesAdminInfiniteQueryKey = (params?: GetApiPropertiesAdminParams,) => {
    return [
    'infinite', `/api/properties/admin`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiPropertiesAdminQueryKey = (params?: GetApiPropertiesAdminParams,) => {
    return [
    `/api/properties/admin`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiPropertiesAdminInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAdmin>>>, TError = unknown>(params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesAdminInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertiesAdmin>>> = ({ signal }) => getApiPropertiesAdmin(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesAdminInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertiesAdmin>>>
export type GetApiPropertiesAdminInfiniteQueryError = unknown


export function useGetApiPropertiesAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAdmin>>>, TError = unknown>(
 params: undefined |  GetApiPropertiesAdminParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAdmin>>>, TError = unknown>(
 params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAdmin>>>, TError = unknown>(
 params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all properties for admin management
 */

export function useGetApiPropertiesAdminInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesAdmin>>>, TError = unknown>(
 params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesAdminInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all properties for admin management
 */
export const prefetchGetApiPropertiesAdminInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesAdminInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiPropertiesAdminQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError = unknown>(params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesAdminQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertiesAdmin>>> = ({ signal }) => getApiPropertiesAdmin(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesAdminQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertiesAdmin>>>
export type GetApiPropertiesAdminQueryError = unknown


export function useGetApiPropertiesAdmin<TData = Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError = unknown>(
 params: undefined |  GetApiPropertiesAdminParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesAdmin<TData = Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError = unknown>(
 params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesAdmin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesAdmin<TData = Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError = unknown>(
 params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all properties for admin management
 */

export function useGetApiPropertiesAdmin<TData = Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError = unknown>(
 params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesAdminQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List all properties for admin management
 */
export const prefetchGetApiPropertiesAdminQuery = async <TData = Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiPropertiesAdminParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesAdmin>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesAdminQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary List property types
 */
export const getApiPropertyTypes = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/types`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiPropertyTypesInfiniteQueryKey = () => {
    return [
    'infinite', `/api/properties/types`
    ] as const;
    }

export const getGetApiPropertyTypesQueryKey = () => {
    return [
    `/api/properties/types`
    ] as const;
    }

    
export const getGetApiPropertyTypesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyTypesInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyTypes>>> = ({ signal }) => getApiPropertyTypes(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyTypesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyTypes>>>
export type GetApiPropertyTypesInfiniteQueryError = unknown


export function useGetApiPropertyTypesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyTypes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyTypesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyTypes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyTypesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List property types
 */

export function useGetApiPropertyTypesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyTypes>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyTypesInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List property types
 */
export const prefetchGetApiPropertyTypesInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyTypesInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiPropertyTypesQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyTypesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyTypes>>> = ({ signal }) => getApiPropertyTypes(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyTypes>>>
export type GetApiPropertyTypesQueryError = unknown


export function useGetApiPropertyTypes<TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyTypes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyTypes<TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyTypes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyTypes<TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List property types
 */

export function useGetApiPropertyTypes<TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List property types
 */
export const prefetchGetApiPropertyTypesQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyTypes>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyTypes>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyTypesQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Create a property type
 */
export const postApiPropertyType = (
    createPropertyTypeDto: CreatePropertyTypeDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/types`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPropertyTypeDto, signal
    },
      );
    }
  


export const getPostApiPropertyTypeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyType>>, TError,{data: CreatePropertyTypeDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyType>>, TError,{data: CreatePropertyTypeDto}, TContext> => {

const mutationKey = ['postApiPropertyType'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPropertyType>>, {data: CreatePropertyTypeDto}> = (props) => {
          const {data} = props ?? {};

          return  postApiPropertyType(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiPropertyTypeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPropertyType>>>
    export type PostApiPropertyTypeMutationBody = CreatePropertyTypeDto
    export type PostApiPropertyTypeMutationError = unknown

    /**
 * @summary Create a property type
 */
export const usePostApiPropertyType = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyType>>, TError,{data: CreatePropertyTypeDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPropertyType>>,
        TError,
        {data: CreatePropertyTypeDto},
        TContext
      > => {

      const mutationOptions = getPostApiPropertyTypeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List media of a property
 */
export const getApiPropertyMedia = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}/media`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiPropertyMediaInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/properties/${id}/media`
    ] as const;
    }

export const getGetApiPropertyMediaQueryKey = (id?: string,) => {
    return [
    `/api/properties/${id}/media`
    ] as const;
    }

    
export const getGetApiPropertyMediaInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyMedia>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyMediaInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyMedia>>> = ({ signal }) => getApiPropertyMedia(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyMediaInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyMedia>>>
export type GetApiPropertyMediaInfiniteQueryError = unknown


export function useGetApiPropertyMediaInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyMedia>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyMedia>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyMediaInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyMedia>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyMedia>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyMediaInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyMedia>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List media of a property
 */

export function useGetApiPropertyMediaInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyMedia>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyMediaInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List media of a property
 */
export const prefetchGetApiPropertyMediaInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyMedia>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyMediaInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiPropertyMediaQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertyMedia>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyMediaQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyMedia>>> = ({ signal }) => getApiPropertyMedia(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyMediaQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyMedia>>>
export type GetApiPropertyMediaQueryError = unknown


export function useGetApiPropertyMedia<TData = Awaited<ReturnType<typeof getApiPropertyMedia>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyMedia>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyMedia<TData = Awaited<ReturnType<typeof getApiPropertyMedia>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyMedia>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyMedia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyMedia<TData = Awaited<ReturnType<typeof getApiPropertyMedia>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List media of a property
 */

export function useGetApiPropertyMedia<TData = Awaited<ReturnType<typeof getApiPropertyMedia>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyMediaQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary List media of a property
 */
export const prefetchGetApiPropertyMediaQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyMedia>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyMedia>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyMediaQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Add media to a property
 */
export const postApiPropertyMedia = (
    id: string,
    createPropertyMediaDto: CreatePropertyMediaDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}/media`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPropertyMediaDto, signal
    },
      );
    }
  


export const getPostApiPropertyMediaMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyMedia>>, TError,{id: string;data: CreatePropertyMediaDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyMedia>>, TError,{id: string;data: CreatePropertyMediaDto}, TContext> => {

const mutationKey = ['postApiPropertyMedia'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPropertyMedia>>, {id: string;data: CreatePropertyMediaDto}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiPropertyMedia(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiPropertyMediaMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPropertyMedia>>>
    export type PostApiPropertyMediaMutationBody = CreatePropertyMediaDto
    export type PostApiPropertyMediaMutationError = unknown

    /**
 * @summary Add media to a property
 */
export const usePostApiPropertyMedia = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyMedia>>, TError,{id: string;data: CreatePropertyMediaDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPropertyMedia>>,
        TError,
        {id: string;data: CreatePropertyMediaDto},
        TContext
      > => {

      const mutationOptions = getPostApiPropertyMediaMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update property media
 */
export const patchApiPropertyMedia = (
    id: string,
    mediaId: string,
    updatePropertyMediaDto: UpdatePropertyMediaDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}/media/${mediaId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePropertyMediaDto
    },
      );
    }
  


export const getPatchApiPropertyMediaMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiPropertyMedia>>, TError,{id: string;mediaId: string;data: UpdatePropertyMediaDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiPropertyMedia>>, TError,{id: string;mediaId: string;data: UpdatePropertyMediaDto}, TContext> => {

const mutationKey = ['patchApiPropertyMedia'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiPropertyMedia>>, {id: string;mediaId: string;data: UpdatePropertyMediaDto}> = (props) => {
          const {id,mediaId,data} = props ?? {};

          return  patchApiPropertyMedia(id,mediaId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiPropertyMediaMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiPropertyMedia>>>
    export type PatchApiPropertyMediaMutationBody = UpdatePropertyMediaDto
    export type PatchApiPropertyMediaMutationError = unknown

    /**
 * @summary Update property media
 */
export const usePatchApiPropertyMedia = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiPropertyMedia>>, TError,{id: string;mediaId: string;data: UpdatePropertyMediaDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiPropertyMedia>>,
        TError,
        {id: string;mediaId: string;data: UpdatePropertyMediaDto},
        TContext
      > => {

      const mutationOptions = getPatchApiPropertyMediaMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Remove media from property
 */
export const deleteApiPropertyMedia = (
    id: string,
    mediaId: string,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}/media/${mediaId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiPropertyMediaMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPropertyMedia>>, TError,{id: string;mediaId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiPropertyMedia>>, TError,{id: string;mediaId: string}, TContext> => {

const mutationKey = ['deleteApiPropertyMedia'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiPropertyMedia>>, {id: string;mediaId: string}> = (props) => {
          const {id,mediaId} = props ?? {};

          return  deleteApiPropertyMedia(id,mediaId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPropertyMediaMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiPropertyMedia>>>
    
    export type DeleteApiPropertyMediaMutationError = unknown

    /**
 * @summary Remove media from property
 */
export const useDeleteApiPropertyMedia = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPropertyMedia>>, TError,{id: string;mediaId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiPropertyMedia>>,
        TError,
        {id: string;mediaId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiPropertyMediaMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Reorder property media
 */
export const postApiPropertyMediaReorder = (
    id: string,
    reorderPropertyMediaDto: ReorderPropertyMediaDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}/media/reorder`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reorderPropertyMediaDto, signal
    },
      );
    }
  


export const getPostApiPropertyMediaReorderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyMediaReorder>>, TError,{id: string;data: ReorderPropertyMediaDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyMediaReorder>>, TError,{id: string;data: ReorderPropertyMediaDto}, TContext> => {

const mutationKey = ['postApiPropertyMediaReorder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPropertyMediaReorder>>, {id: string;data: ReorderPropertyMediaDto}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiPropertyMediaReorder(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiPropertyMediaReorderMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPropertyMediaReorder>>>
    export type PostApiPropertyMediaReorderMutationBody = ReorderPropertyMediaDto
    export type PostApiPropertyMediaReorderMutationError = unknown

    /**
 * @summary Reorder property media
 */
export const usePostApiPropertyMediaReorder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPropertyMediaReorder>>, TError,{id: string;data: ReorderPropertyMediaDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPropertyMediaReorder>>,
        TError,
        {id: string;data: ReorderPropertyMediaDto},
        TContext
      > => {

      const mutationOptions = getPostApiPropertyMediaReorderMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Set primary media for property
 */
export const patchApiPropertyMediaSetPrimary = (
    id: string,
    mediaId: string,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}/media/${mediaId}/set-primary`, method: 'PATCH'
    },
      );
    }
  


export const getPatchApiPropertyMediaSetPrimaryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiPropertyMediaSetPrimary>>, TError,{id: string;mediaId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiPropertyMediaSetPrimary>>, TError,{id: string;mediaId: string}, TContext> => {

const mutationKey = ['patchApiPropertyMediaSetPrimary'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiPropertyMediaSetPrimary>>, {id: string;mediaId: string}> = (props) => {
          const {id,mediaId} = props ?? {};

          return  patchApiPropertyMediaSetPrimary(id,mediaId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiPropertyMediaSetPrimaryMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiPropertyMediaSetPrimary>>>
    
    export type PatchApiPropertyMediaSetPrimaryMutationError = unknown

    /**
 * @summary Set primary media for property
 */
export const usePatchApiPropertyMediaSetPrimary = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiPropertyMediaSetPrimary>>, TError,{id: string;mediaId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiPropertyMediaSetPrimary>>,
        TError,
        {id: string;mediaId: string},
        TContext
      > => {

      const mutationOptions = getPatchApiPropertyMediaSetPrimaryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get property by propertyCode
 */
export const getApiPropertyCode = (
    propertyCode: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/code/${propertyCode}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiPropertyCodeInfiniteQueryKey = (propertyCode?: string,) => {
    return [
    'infinite', `/api/properties/code/${propertyCode}`
    ] as const;
    }

export const getGetApiPropertyCodeQueryKey = (propertyCode?: string,) => {
    return [
    `/api/properties/code/${propertyCode}`
    ] as const;
    }

    
export const getGetApiPropertyCodeInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyCode>>>, TError = unknown>(propertyCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyCodeInfiniteQueryKey(propertyCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyCode>>> = ({ signal }) => getApiPropertyCode(propertyCode, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(propertyCode),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyCodeInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyCode>>>
export type GetApiPropertyCodeInfiniteQueryError = unknown


export function useGetApiPropertyCodeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyCode>>>, TError = unknown>(
 propertyCode: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyCode>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyCode>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyCodeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyCode>>>, TError = unknown>(
 propertyCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyCode>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyCode>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyCodeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyCode>>>, TError = unknown>(
 propertyCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get property by propertyCode
 */

export function useGetApiPropertyCodeInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyCode>>>, TError = unknown>(
 propertyCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyCodeInfiniteQueryOptions(propertyCode,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get property by propertyCode
 */
export const prefetchGetApiPropertyCodeInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyCode>>, TError = unknown>(
 queryClient: QueryClient, propertyCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyCodeInfiniteQueryOptions(propertyCode,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiPropertyCodeQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertyCode>>, TError = unknown>(propertyCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyCodeQueryKey(propertyCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyCode>>> = ({ signal }) => getApiPropertyCode(propertyCode, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(propertyCode),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyCodeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyCode>>>
export type GetApiPropertyCodeQueryError = unknown


export function useGetApiPropertyCode<TData = Awaited<ReturnType<typeof getApiPropertyCode>>, TError = unknown>(
 propertyCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyCode>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyCode>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyCode<TData = Awaited<ReturnType<typeof getApiPropertyCode>>, TError = unknown>(
 propertyCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyCode>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyCode>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyCode<TData = Awaited<ReturnType<typeof getApiPropertyCode>>, TError = unknown>(
 propertyCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get property by propertyCode
 */

export function useGetApiPropertyCode<TData = Awaited<ReturnType<typeof getApiPropertyCode>>, TError = unknown>(
 propertyCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyCodeQueryOptions(propertyCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get property by propertyCode
 */
export const prefetchGetApiPropertyCodeQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyCode>>, TError = unknown>(
 queryClient: QueryClient, propertyCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyCode>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyCodeQueryOptions(propertyCode,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Get property by ID
 */
export const getApiPropertyId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiPropertyIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/properties/${id}`
    ] as const;
    }

export const getGetApiPropertyIdQueryKey = (id?: string,) => {
    return [
    `/api/properties/${id}`
    ] as const;
    }

    
export const getGetApiPropertyIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = unknown>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyId>>> = ({ signal }) => getApiPropertyId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyId>>>
export type GetApiPropertyIdInfiniteQueryError = unknown


export function useGetApiPropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = unknown>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get property by ID
 */

export function useGetApiPropertyIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertyId>>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get property by ID
 */
export const prefetchGetApiPropertyIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiPropertyIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertyIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertyId>>> = ({ signal }) => getApiPropertyId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertyIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertyId>>>
export type GetApiPropertyIdQueryError = unknown


export function useGetApiPropertyId<TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyId<TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertyId>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertyId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertyId<TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get property by ID
 */

export function useGetApiPropertyId<TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertyIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get property by ID
 */
export const prefetchGetApiPropertyIdQuery = async <TData = Awaited<ReturnType<typeof getApiPropertyId>>, TError = unknown>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertyId>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertyIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Update a property
 */
export const patchApiProperty = (
    id: string,
    updatePropertyDto: UpdatePropertyDto,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePropertyDto
    },
      );
    }
  


export const getPatchApiPropertyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProperty>>, TError,{id: string;data: UpdatePropertyDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchApiProperty>>, TError,{id: string;data: UpdatePropertyDto}, TContext> => {

const mutationKey = ['patchApiProperty'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiProperty>>, {id: string;data: UpdatePropertyDto}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiProperty(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiProperty>>>
    export type PatchApiPropertyMutationBody = UpdatePropertyDto
    export type PatchApiPropertyMutationError = unknown

    /**
 * @summary Update a property
 */
export const usePatchApiProperty = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiProperty>>, TError,{id: string;data: UpdatePropertyDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiProperty>>,
        TError,
        {id: string;data: UpdatePropertyDto},
        TContext
      > => {

      const mutationOptions = getPatchApiPropertyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Soft delete a property
 */
export const deleteApiProperty = (
    id: string,
 ) => {
      
      
      return customInstance<unknown>(
      {url: `/api/properties/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteApiPropertyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProperty>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiProperty>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiProperty'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiProperty>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiProperty(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPropertyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiProperty>>>
    
    export type DeleteApiPropertyMutationError = unknown

    /**
 * @summary Soft delete a property
 */
export const useDeleteApiProperty = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiProperty>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiProperty>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiPropertyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    