/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiCommissionReportParams,
  GetApiSalesReportParams,
  GetApiTeamPerformanceReportParams
} from '../models';

import { customInstance } from '../mutator/custom-instance';





/**
 * @summary Sales summary report (deals, leads, appointments, reservations)
 */
export const getApiSalesReport = (
    params?: GetApiSalesReportParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/reports/sales`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiSalesReportInfiniteQueryKey = (params?: GetApiSalesReportParams,) => {
    return [
    'infinite', `/api/reports/sales`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiSalesReportQueryKey = (params?: GetApiSalesReportParams,) => {
    return [
    `/api/reports/sales`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiSalesReportInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiSalesReport>>>, TError = unknown>(params?: GetApiSalesReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSalesReportInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSalesReport>>> = ({ signal }) => getApiSalesReport(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSalesReportInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSalesReport>>>
export type GetApiSalesReportInfiniteQueryError = unknown


export function useGetApiSalesReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiSalesReport>>>, TError = unknown>(
 params: undefined |  GetApiSalesReportParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSalesReport>>,
          TError,
          Awaited<ReturnType<typeof getApiSalesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSalesReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiSalesReport>>>, TError = unknown>(
 params?: GetApiSalesReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSalesReport>>,
          TError,
          Awaited<ReturnType<typeof getApiSalesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSalesReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiSalesReport>>>, TError = unknown>(
 params?: GetApiSalesReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sales summary report (deals, leads, appointments, reservations)
 */

export function useGetApiSalesReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiSalesReport>>>, TError = unknown>(
 params?: GetApiSalesReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSalesReportInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Sales summary report (deals, leads, appointments, reservations)
 */
export const prefetchGetApiSalesReportInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiSalesReport>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiSalesReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiSalesReportInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiSalesReportQueryOptions = <TData = Awaited<ReturnType<typeof getApiSalesReport>>, TError = unknown>(params?: GetApiSalesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSalesReportQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSalesReport>>> = ({ signal }) => getApiSalesReport(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSalesReportQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSalesReport>>>
export type GetApiSalesReportQueryError = unknown


export function useGetApiSalesReport<TData = Awaited<ReturnType<typeof getApiSalesReport>>, TError = unknown>(
 params: undefined |  GetApiSalesReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSalesReport>>,
          TError,
          Awaited<ReturnType<typeof getApiSalesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSalesReport<TData = Awaited<ReturnType<typeof getApiSalesReport>>, TError = unknown>(
 params?: GetApiSalesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSalesReport>>,
          TError,
          Awaited<ReturnType<typeof getApiSalesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSalesReport<TData = Awaited<ReturnType<typeof getApiSalesReport>>, TError = unknown>(
 params?: GetApiSalesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sales summary report (deals, leads, appointments, reservations)
 */

export function useGetApiSalesReport<TData = Awaited<ReturnType<typeof getApiSalesReport>>, TError = unknown>(
 params?: GetApiSalesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSalesReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Sales summary report (deals, leads, appointments, reservations)
 */
export const prefetchGetApiSalesReportQuery = async <TData = Awaited<ReturnType<typeof getApiSalesReport>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiSalesReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSalesReport>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiSalesReportQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Commission summary report
 */
export const getApiCommissionReport = (
    params?: GetApiCommissionReportParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/reports/commission`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiCommissionReportInfiniteQueryKey = (params?: GetApiCommissionReportParams,) => {
    return [
    'infinite', `/api/reports/commission`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiCommissionReportQueryKey = (params?: GetApiCommissionReportParams,) => {
    return [
    `/api/reports/commission`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCommissionReportInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiCommissionReport>>>, TError = unknown>(params?: GetApiCommissionReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCommissionReportInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCommissionReport>>> = ({ signal }) => getApiCommissionReport(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCommissionReportInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCommissionReport>>>
export type GetApiCommissionReportInfiniteQueryError = unknown


export function useGetApiCommissionReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCommissionReport>>>, TError = unknown>(
 params: undefined |  GetApiCommissionReportParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommissionReport>>,
          TError,
          Awaited<ReturnType<typeof getApiCommissionReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommissionReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCommissionReport>>>, TError = unknown>(
 params?: GetApiCommissionReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommissionReport>>,
          TError,
          Awaited<ReturnType<typeof getApiCommissionReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommissionReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCommissionReport>>>, TError = unknown>(
 params?: GetApiCommissionReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Commission summary report
 */

export function useGetApiCommissionReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiCommissionReport>>>, TError = unknown>(
 params?: GetApiCommissionReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCommissionReportInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Commission summary report
 */
export const prefetchGetApiCommissionReportInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiCommissionReport>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCommissionReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCommissionReportInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiCommissionReportQueryOptions = <TData = Awaited<ReturnType<typeof getApiCommissionReport>>, TError = unknown>(params?: GetApiCommissionReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCommissionReportQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCommissionReport>>> = ({ signal }) => getApiCommissionReport(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCommissionReportQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCommissionReport>>>
export type GetApiCommissionReportQueryError = unknown


export function useGetApiCommissionReport<TData = Awaited<ReturnType<typeof getApiCommissionReport>>, TError = unknown>(
 params: undefined |  GetApiCommissionReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommissionReport>>,
          TError,
          Awaited<ReturnType<typeof getApiCommissionReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommissionReport<TData = Awaited<ReturnType<typeof getApiCommissionReport>>, TError = unknown>(
 params?: GetApiCommissionReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCommissionReport>>,
          TError,
          Awaited<ReturnType<typeof getApiCommissionReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCommissionReport<TData = Awaited<ReturnType<typeof getApiCommissionReport>>, TError = unknown>(
 params?: GetApiCommissionReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Commission summary report
 */

export function useGetApiCommissionReport<TData = Awaited<ReturnType<typeof getApiCommissionReport>>, TError = unknown>(
 params?: GetApiCommissionReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCommissionReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Commission summary report
 */
export const prefetchGetApiCommissionReportQuery = async <TData = Awaited<ReturnType<typeof getApiCommissionReport>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiCommissionReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCommissionReport>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiCommissionReportQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Property summary report
 */
export const getApiPropertiesReport = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/reports/properties`, method: 'GET', signal
    },
      );
    }
  



export const getGetApiPropertiesReportInfiniteQueryKey = () => {
    return [
    'infinite', `/api/reports/properties`
    ] as const;
    }

export const getGetApiPropertiesReportQueryKey = () => {
    return [
    `/api/reports/properties`
    ] as const;
    }

    
export const getGetApiPropertiesReportInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesReport>>>, TError = unknown>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesReportInfiniteQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertiesReport>>> = ({ signal }) => getApiPropertiesReport(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesReportInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertiesReport>>>
export type GetApiPropertiesReportInfiniteQueryError = unknown


export function useGetApiPropertiesReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesReport>>>, TError = unknown>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesReport>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesReport>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesReport>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesReport>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Property summary report
 */

export function useGetApiPropertiesReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiPropertiesReport>>>, TError = unknown>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesReportInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Property summary report
 */
export const prefetchGetApiPropertiesReportInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiPropertiesReport>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesReportInfiniteQueryOptions(options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiPropertiesReportQueryOptions = <TData = Awaited<ReturnType<typeof getApiPropertiesReport>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPropertiesReportQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPropertiesReport>>> = ({ signal }) => getApiPropertiesReport(signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPropertiesReportQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPropertiesReport>>>
export type GetApiPropertiesReportQueryError = unknown


export function useGetApiPropertiesReport<TData = Awaited<ReturnType<typeof getApiPropertiesReport>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesReport>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesReport<TData = Awaited<ReturnType<typeof getApiPropertiesReport>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPropertiesReport>>,
          TError,
          Awaited<ReturnType<typeof getApiPropertiesReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPropertiesReport<TData = Awaited<ReturnType<typeof getApiPropertiesReport>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Property summary report
 */

export function useGetApiPropertiesReport<TData = Awaited<ReturnType<typeof getApiPropertiesReport>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPropertiesReportQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Property summary report
 */
export const prefetchGetApiPropertiesReportQuery = async <TData = Awaited<ReturnType<typeof getApiPropertiesReport>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPropertiesReport>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiPropertiesReportQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * @summary Team performance report by user
 */
export const getApiTeamPerformanceReport = (
    params?: GetApiTeamPerformanceReportParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/reports/team-performance`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetApiTeamPerformanceReportInfiniteQueryKey = (params?: GetApiTeamPerformanceReportParams,) => {
    return [
    'infinite', `/api/reports/team-performance`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiTeamPerformanceReportQueryKey = (params?: GetApiTeamPerformanceReportParams,) => {
    return [
    `/api/reports/team-performance`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiTeamPerformanceReportInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>>, TError = unknown>(params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTeamPerformanceReportInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>> = ({ signal }) => getApiTeamPerformanceReport(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTeamPerformanceReportInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>>
export type GetApiTeamPerformanceReportInfiniteQueryError = unknown


export function useGetApiTeamPerformanceReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>>, TError = unknown>(
 params: undefined |  GetApiTeamPerformanceReportParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeamPerformanceReport>>,
          TError,
          Awaited<ReturnType<typeof getApiTeamPerformanceReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamPerformanceReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>>, TError = unknown>(
 params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeamPerformanceReport>>,
          TError,
          Awaited<ReturnType<typeof getApiTeamPerformanceReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamPerformanceReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>>, TError = unknown>(
 params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Team performance report by user
 */

export function useGetApiTeamPerformanceReportInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>>, TError = unknown>(
 params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTeamPerformanceReportInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Team performance report by user
 */
export const prefetchGetApiTeamPerformanceReportInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTeamPerformanceReportInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiTeamPerformanceReportQueryOptions = <TData = Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError = unknown>(params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTeamPerformanceReportQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>> = ({ signal }) => getApiTeamPerformanceReport(params, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTeamPerformanceReportQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>>
export type GetApiTeamPerformanceReportQueryError = unknown


export function useGetApiTeamPerformanceReport<TData = Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError = unknown>(
 params: undefined |  GetApiTeamPerformanceReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeamPerformanceReport>>,
          TError,
          Awaited<ReturnType<typeof getApiTeamPerformanceReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamPerformanceReport<TData = Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError = unknown>(
 params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTeamPerformanceReport>>,
          TError,
          Awaited<ReturnType<typeof getApiTeamPerformanceReport>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTeamPerformanceReport<TData = Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError = unknown>(
 params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Team performance report by user
 */

export function useGetApiTeamPerformanceReport<TData = Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError = unknown>(
 params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTeamPerformanceReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Team performance report by user
 */
export const prefetchGetApiTeamPerformanceReportQuery = async <TData = Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError = unknown>(
 queryClient: QueryClient, params?: GetApiTeamPerformanceReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTeamPerformanceReport>>, TError, TData>>, }

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiTeamPerformanceReportQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



