/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateUserDto
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postApiUserResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiUserResponseError = (postApiUserResponseDefault) & {
  headers: Headers;
};

export type postApiUserResponse = (postApiUserResponseError)

export const getPostApiUserUrl = () => {




  return `/api/v1/users`
}

/**
 * @summary Register a new user
 */
export const postApiUser = async (createUserDto: CreateUserDto, options?: RequestInit): Promise<postApiUserResponse> => {

  return useCustomClient<postApiUserResponse>(getPostApiUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUserDto)
  }
);}





export const getPostApiUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUser>>, TError,{data: BodyType<CreateUserDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUser>>, TError,{data: BodyType<CreateUserDto>}, TContext> => {

const mutationKey = ['postApiUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUser>>, {data: BodyType<CreateUserDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiUserMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUser>>>
    export type PostApiUserMutationBody = BodyType<CreateUserDto>
    export type PostApiUserMutationError = ErrorType<unknown>

    /**
 * @summary Register a new user
 */
export const usePostApiUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUser>>, TError,{data: BodyType<CreateUserDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUser>>,
        TError,
        {data: BodyType<CreateUserDto>},
        TContext
      > => {
      return useMutation(getPostApiUserMutationOptions(options), queryClient);
    }
