/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateWorkflowDto,
  GetApiWorkflowsParams
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiWorkflowsResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiWorkflowsResponseError = (getApiWorkflowsResponseDefault) & {
  headers: Headers;
};

export type getApiWorkflowsResponse = (getApiWorkflowsResponseError)

export const getGetApiWorkflowsUrl = (params?: GetApiWorkflowsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/workflows?${stringifiedParams}` : `/api/workflows`
}

/**
 * @summary List workflow definitions
 */
export const getApiWorkflows = async (params?: GetApiWorkflowsParams, options?: RequestInit): Promise<getApiWorkflowsResponse> => {

  return useCustomClient<getApiWorkflowsResponse>(getGetApiWorkflowsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiWorkflowsInfiniteQueryKey = (params?: GetApiWorkflowsParams,) => {
    return [
    'infinite', `/api/workflows`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetApiWorkflowsQueryKey = (params?: GetApiWorkflowsParams,) => {
    return [
    `/api/workflows`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiWorkflowsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = ErrorType<unknown>>(params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowsInfiniteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflows>>> = ({ signal }) => getApiWorkflows(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflows>>>
export type GetApiWorkflowsInfiniteQueryError = ErrorType<unknown>


export function useGetApiWorkflowsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiWorkflowsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = ErrorType<unknown>>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = ErrorType<unknown>>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List workflow definitions
 */

export function useGetApiWorkflowsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflows>>>, TError = ErrorType<unknown>>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowsInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List workflow definitions
 */
export const prefetchGetApiWorkflowsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiWorkflowsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowsInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiWorkflowsQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = ErrorType<unknown>>(params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflows>>> = ({ signal }) => getApiWorkflows(params, { signal, ...requestOptions });





   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflows>>>
export type GetApiWorkflowsQueryError = ErrorType<unknown>


export function useGetApiWorkflows<TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiWorkflowsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflows<TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = ErrorType<unknown>>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflows>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflows<TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = ErrorType<unknown>>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List workflow definitions
 */

export function useGetApiWorkflows<TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = ErrorType<unknown>>(
 params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List workflow definitions
 */
export const prefetchGetApiWorkflowsQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflows>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiWorkflowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflows>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postApiWorkflowResponseDefault = {
  data: unknown
  status: number
}

;
export type postApiWorkflowResponseError = (postApiWorkflowResponseDefault) & {
  headers: Headers;
};

export type postApiWorkflowResponse = (postApiWorkflowResponseError)

export const getPostApiWorkflowUrl = () => {




  return `/api/workflows`
}

/**
 * @summary Create a workflow definition with states and transitions
 */
export const postApiWorkflow = async (createWorkflowDto: CreateWorkflowDto, options?: RequestInit): Promise<postApiWorkflowResponse> => {

  return useCustomClient<postApiWorkflowResponse>(getPostApiWorkflowUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWorkflowDto)
  }
);}





export const getPostApiWorkflowMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkflow>>, TError,{data: BodyType<CreateWorkflowDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiWorkflow>>, TError,{data: BodyType<CreateWorkflowDto>}, TContext> => {

const mutationKey = ['postApiWorkflow'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiWorkflow>>, {data: BodyType<CreateWorkflowDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiWorkflow(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiWorkflowMutationResult = NonNullable<Awaited<ReturnType<typeof postApiWorkflow>>>
    export type PostApiWorkflowMutationBody = BodyType<CreateWorkflowDto>
    export type PostApiWorkflowMutationError = ErrorType<unknown>

    /**
 * @summary Create a workflow definition with states and transitions
 */
export const usePostApiWorkflow = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiWorkflow>>, TError,{data: BodyType<CreateWorkflowDto>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiWorkflow>>,
        TError,
        {data: BodyType<CreateWorkflowDto>},
        TContext
      > => {
      return useMutation(getPostApiWorkflowMutationOptions(options), queryClient);
    }
    export type getApiWorkflowIdResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiWorkflowIdResponseError = (getApiWorkflowIdResponseDefault) & {
  headers: Headers;
};

export type getApiWorkflowIdResponse = (getApiWorkflowIdResponseError)

export const getGetApiWorkflowIdUrl = (id: string,) => {




  return `/api/workflows/${id}`
}

/**
 * @summary Get workflow definition by ID
 */
export const getApiWorkflowId = async (id: string, options?: RequestInit): Promise<getApiWorkflowIdResponse> => {

  return useCustomClient<getApiWorkflowIdResponse>(getGetApiWorkflowIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiWorkflowIdInfiniteQueryKey = (id: string,) => {
    return [
    'infinite', `/api/workflows/${id}`
    ] as const;
    }

export const getGetApiWorkflowIdQueryKey = (id: string,) => {
    return [
    `/api/workflows/${id}`
    ] as const;
    }


export const getGetApiWorkflowIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowIdInfiniteQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowId>>> = ({ signal }) => getApiWorkflowId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowId>>>
export type GetApiWorkflowIdInfiniteQueryError = ErrorType<unknown>


export function useGetApiWorkflowIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get workflow definition by ID
 */

export function useGetApiWorkflowIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowId>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get workflow definition by ID
 */
export const prefetchGetApiWorkflowIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiWorkflowIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowId>>> = ({ signal }) => getApiWorkflowId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowId>>>
export type GetApiWorkflowIdQueryError = ErrorType<unknown>


export function useGetApiWorkflowId<TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowId<TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowId>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowId<TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get workflow definition by ID
 */

export function useGetApiWorkflowId<TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get workflow definition by ID
 */
export const prefetchGetApiWorkflowIdQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowId>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type getApiWorkflowTransitionsResponseDefault = {
  data: unknown
  status: number
}

;
export type getApiWorkflowTransitionsResponseError = (getApiWorkflowTransitionsResponseDefault) & {
  headers: Headers;
};

export type getApiWorkflowTransitionsResponse = (getApiWorkflowTransitionsResponseError)

export const getGetApiWorkflowTransitionsUrl = (id: string,
    currentStateCode: string,) => {




  return `/api/workflows/${id}/transitions/${currentStateCode}`
}

/**
 * @summary Get available transitions from current state
 */
export const getApiWorkflowTransitions = async (id: string,
    currentStateCode: string, options?: RequestInit): Promise<getApiWorkflowTransitionsResponse> => {

  return useCustomClient<getApiWorkflowTransitionsResponse>(getGetApiWorkflowTransitionsUrl(id,currentStateCode),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiWorkflowTransitionsInfiniteQueryKey = (id: string,
    currentStateCode: string,) => {
    return [
    'infinite', `/api/workflows/${id}/transitions/${currentStateCode}`
    ] as const;
    }

export const getGetApiWorkflowTransitionsQueryKey = (id: string,
    currentStateCode: string,) => {
    return [
    `/api/workflows/${id}/transitions/${currentStateCode}`
    ] as const;
    }


export const getGetApiWorkflowTransitionsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowTransitions>>>, TError = ErrorType<unknown>>(id: string,
    currentStateCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowTransitionsInfiniteQueryKey(id,currentStateCode);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowTransitions>>> = ({ signal }) => getApiWorkflowTransitions(id,currentStateCode, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && currentStateCode !== null && currentStateCode !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowTransitionsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowTransitions>>>
export type GetApiWorkflowTransitionsInfiniteQueryError = ErrorType<unknown>


export function useGetApiWorkflowTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowTransitions>>>, TError = ErrorType<unknown>>(
 id: string,
    currentStateCode: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowTransitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowTransitions>>>, TError = ErrorType<unknown>>(
 id: string,
    currentStateCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowTransitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowTransitions>>>, TError = ErrorType<unknown>>(
 id: string,
    currentStateCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get available transitions from current state
 */

export function useGetApiWorkflowTransitionsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiWorkflowTransitions>>>, TError = ErrorType<unknown>>(
 id: string,
    currentStateCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowTransitionsInfiniteQueryOptions(id,currentStateCode,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get available transitions from current state
 */
export const prefetchGetApiWorkflowTransitionsInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string,
    currentStateCode: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowTransitionsInfiniteQueryOptions(id,currentStateCode,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}





export const getGetApiWorkflowTransitionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError = ErrorType<unknown>>(id: string,
    currentStateCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiWorkflowTransitionsQueryKey(id,currentStateCode);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkflowTransitions>>> = ({ signal }) => getApiWorkflowTransitions(id,currentStateCode, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && currentStateCode !== null && currentStateCode !== undefined,  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiWorkflowTransitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiWorkflowTransitions>>>
export type GetApiWorkflowTransitionsQueryError = ErrorType<unknown>


export function useGetApiWorkflowTransitions<TData = Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError = ErrorType<unknown>>(
 id: string,
    currentStateCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowTransitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowTransitions<TData = Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError = ErrorType<unknown>>(
 id: string,
    currentStateCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkflowTransitions>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkflowTransitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiWorkflowTransitions<TData = Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError = ErrorType<unknown>>(
 id: string,
    currentStateCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get available transitions from current state
 */

export function useGetApiWorkflowTransitions<TData = Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError = ErrorType<unknown>>(
 id: string,
    currentStateCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiWorkflowTransitionsQueryOptions(id,currentStateCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Get available transitions from current state
 */
export const prefetchGetApiWorkflowTransitionsQuery = async <TData = Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string,
    currentStateCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiWorkflowTransitions>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiWorkflowTransitionsQueryOptions(id,currentStateCode,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





