/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export interface AssignUsersDto {
  /** User IDs to assign to this role */
  userIds: string[];
}
