/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { CreateExportJobDtoExportType } from './createExportJobDtoExportType';
import type { CreateExportJobDtoFiltersJson } from './createExportJobDtoFiltersJson';

export interface CreateExportJobDto {
  exportType: CreateExportJobDtoExportType;
  filtersJson?: CreateExportJobDtoFiltersJson;
}
