/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type CreatePropertyDtoVerificationStatus = typeof CreatePropertyDtoVerificationStatus[keyof typeof CreatePropertyDtoVerificationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePropertyDtoVerificationStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
} as const;
