/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { CreateProjectDtoStatus } from './createProjectDtoStatus';

export interface CreateProjectDto {
  name: string;
  code: string;
  developer?: string;
  provinceId?: string;
  districtId?: string;
  status?: CreateProjectDtoStatus;
}
