/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { CreateProjectDtoStatus } from './createProjectDtoStatus';

export interface CreateProjectDto {
  name: string;
  /** Auto-generated as DA-DDMMyy-NNN if omitted */
  code?: string;
  developer?: string;
  provinceId?: string;
  districtId?: string;
  status?: CreateProjectDtoStatus;
}
