/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type CreateLeadDisputeDtoConflictType = typeof CreateLeadDisputeDtoConflictType[keyof typeof CreateLeadDisputeDtoConflictType];


export const CreateLeadDisputeDtoConflictType = {
  DOUBLE_ASSIGNMENT: 'DOUBLE_ASSIGNMENT',
  SOURCE_CONFLICT: 'SOURCE_CONFLICT',
  TIMELINE_DISPUTE: 'TIMELINE_DISPUTE',
  OTHER: 'OTHER',
} as const;
