/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type CreatePropertyMediaDtoType = typeof CreatePropertyMediaDtoType[keyof typeof CreatePropertyMediaDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePropertyMediaDtoType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  TOUR_360: 'TOUR_360',
  FLOOR_PLAN: 'FLOOR_PLAN',
  DOCUMENT: 'DOCUMENT',
} as const;
