/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { CreateFieldGroupDtoEntityType } from './createFieldGroupDtoEntityType';

export interface CreateFieldGroupDto {
  entityType: CreateFieldGroupDtoEntityType;
  name: string;
  code: string;
  sortOrder?: number;
}
