/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { CreateReservationDtoReservationType } from './createReservationDtoReservationType';

export interface CreateReservationDto {
  dealId: string;
  propertyId: string;
  customerId?: string;
  reservationType: CreateReservationDtoReservationType;
  startsAt: string;
  expiresAt: string;
  note?: string;
}
