/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { CreateLocationDtoType } from './createLocationDtoType';
import type { CreateLocationDtoStatus } from './createLocationDtoStatus';

export interface CreateLocationDto {
  name: string;
  code: string;
  type: CreateLocationDtoType;
  slug?: string;
  parentId?: string;
  sortOrder?: number;
  status?: CreateLocationDtoStatus;
}
