/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type CreateVisibilityPolicyDtoEntityType = typeof CreateVisibilityPolicyDtoEntityType[keyof typeof CreateVisibilityPolicyDtoEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateVisibilityPolicyDtoEntityType = {
  PROPERTY: 'PROPERTY',
  CUSTOMER: 'CUSTOMER',
  LEAD: 'LEAD',
  DEAL: 'DEAL',
  OWNER_PROFILE: 'OWNER_PROFILE',
} as const;
