/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type CreateNotificationRuleDtoReceiverType = typeof CreateNotificationRuleDtoReceiverType[keyof typeof CreateNotificationRuleDtoReceiverType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateNotificationRuleDtoReceiverType = {
  SALES_AGENT: 'SALES_AGENT',
  SALES_MANAGER: 'SALES_MANAGER',
  TEAM_LEAD: 'TEAM_LEAD',
  ALL_USERS: 'ALL_USERS',
} as const;
