/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type CreateTenantDtoType = typeof CreateTenantDtoType[keyof typeof CreateTenantDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTenantDtoType = {
  AGENCY: 'AGENCY',
  DEVELOPER: 'DEVELOPER',
  DISTRIBUTOR: 'DISTRIBUTOR',
  PLATFORM_INTERNAL: 'PLATFORM_INTERNAL',
} as const;
