/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export interface CreatePropertyContactDto {
  /** UUID of the Property record */
  propertyId: string;
  /** UUID of the user who will receive this contact request (the property owner/sales) */
  recipientUserId: string;
  userName: string;
  userPhone: string;
  userContent?: string;
}
