/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type GetApiVisibilityPoliciesEntityType = typeof GetApiVisibilityPoliciesEntityType[keyof typeof GetApiVisibilityPoliciesEntityType];


export const GetApiVisibilityPoliciesEntityType = {
  PROPERTY: 'PROPERTY',
  CUSTOMER: 'CUSTOMER',
  LEAD: 'LEAD',
  DEAL: 'DEAL',
  OWNER_PROFILE: 'OWNER_PROFILE',
} as const;
