/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type GetApiAuditLogsParams = {
userId?: string;
action?: string;
entityType?: string;
entityId?: string;
startDate?: string;
endDate?: string;
page?: string;
pageSize?: string;
};
