/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type GetApiPropertiesTransactionType = typeof GetApiPropertiesTransactionType[keyof typeof GetApiPropertiesTransactionType];


export const GetApiPropertiesTransactionType = {
  SALE: 'SALE',
  RENT: 'RENT',
  TRANSFER: 'TRANSFER',
  INVESTMENT: 'INVESTMENT',
} as const;
