/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { GetApiNotificationTemplatesChannel } from './getApiNotificationTemplatesChannel';

export type GetApiNotificationTemplatesParams = {
channel?: GetApiNotificationTemplatesChannel;
};
