/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type GetApiDealsStatus = typeof GetApiDealsStatus[keyof typeof GetApiDealsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiDealsStatus = {
  SOFT_RESERVED: 'SOFT_RESERVED',
  NEGOTIATING: 'NEGOTIATING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
} as const;
