/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { GetApiRolesStatus } from './getApiRolesStatus';

export type GetApiRolesParams = {
search?: string;
status?: GetApiRolesStatus;
};
