/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type GetApiAppointmentsAdminStatus = typeof GetApiAppointmentsAdminStatus[keyof typeof GetApiAppointmentsAdminStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAppointmentsAdminStatus = {
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
} as const;
