/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type RegisterDtoGender = typeof RegisterDtoGender[keyof typeof RegisterDtoGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;
