/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { ReorderMediaItemDto } from './reorderMediaItemDto';

export interface ReorderPropertyMediaDto {
  /** Array of media items with new sort order */
  items: ReorderMediaItemDto[];
}
