/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { ReplaceUserDtoStatus } from './replaceUserDtoStatus';

export interface ReplaceUserDto {
  fullName: string;
  email: string;
  /** @minLength 10 */
  password: string;
  phone?: string;
  avatarUrl?: string;
  status: ReplaceUserDtoStatus;
}
