/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export interface SetGroupFieldsDto {
  /** Danh sách field IDs thuộc group (thay toàn bộ) */
  fieldIds: string[];
}
