/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export interface UpdateFieldGroupDto {
  name?: string;
  code?: string;
  propertyTypeId?: string;
  sortOrder?: number;
  status?: string;
}
