/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { PermissionEntryDto } from './permissionEntryDto';

export interface UpdatePermissionsDto {
  /** Full list of permissions for the role (replaces existing) */
  permissions: PermissionEntryDto[];
}
