/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type UpdateCustomerDtoStatus = typeof UpdateCustomerDtoStatus[keyof typeof UpdateCustomerDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateCustomerDtoStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BLACKLISTED: 'BLACKLISTED',
} as const;
