/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { UpdateImportJobDtoStatus } from './updateImportJobDtoStatus';

export interface UpdateImportJobDto {
  status: UpdateImportJobDtoStatus;
  totalRows?: number;
  successRows?: number;
  failedRows?: number;
}
