/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { UpdateLeadDtoStatus } from './updateLeadDtoStatus';
import type { UpdateLeadDtoDuplicateStatus } from './updateLeadDtoDuplicateStatus';

export interface UpdateLeadDto {
  status?: UpdateLeadDtoStatus;
  assignedSalesId?: string;
  assignedTeamId?: string;
  phoneNormalized?: string;
  protectionUntil?: string;
  duplicateStatus?: UpdateLeadDtoDuplicateStatus;
  metadata?: string;
}
