/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type UpdateProjectDtoStatus = typeof UpdateProjectDtoStatus[keyof typeof UpdateProjectDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProjectDtoStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
