/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export interface UpdateNewsDto {
  /** ID of the thumbnail File record */
  thumbnailId?: string;
  title?: string;
  description?: string;
  content?: string;
  /** UUID of the NewsCategory record */
  categoryNewsId?: string;
}
