/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type UpdatePropertyDtoVerificationStatus = typeof UpdatePropertyDtoVerificationStatus[keyof typeof UpdatePropertyDtoVerificationStatus];


export const UpdatePropertyDtoVerificationStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
} as const;
