/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type UpdateNotificationRuleDtoChannel = typeof UpdateNotificationRuleDtoChannel[keyof typeof UpdateNotificationRuleDtoChannel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateNotificationRuleDtoChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
  IN_APP: 'IN_APP',
} as const;
