/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */

export type VisibilityRuleDtoMaskType = typeof VisibilityRuleDtoMaskType[keyof typeof VisibilityRuleDtoMaskType];


export const VisibilityRuleDtoMaskType = {
  MASK_ALL: 'MASK_ALL',
  MASK_ALL_EXCEPT_LAST_3: 'MASK_ALL_EXCEPT_LAST_3',
  MASK_ALL_EXCEPT_FIRST_2: 'MASK_ALL_EXCEPT_FIRST_2',
  CUSTOM: 'CUSTOM',
} as const;
