/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * RealHub API
 * Multi-tenant Real Estate Platform API
 * OpenAPI spec version: v1
 */
import type { VisibilityRuleDtoVisibilityLevel } from './visibilityRuleDtoVisibilityLevel';
import type { VisibilityRuleDtoMaskType } from './visibilityRuleDtoMaskType';
import type { VisibilityRuleDtoConditionJson } from './visibilityRuleDtoConditionJson';

export interface VisibilityRuleDto {
  fieldKey: string;
  roleCode: string;
  visibilityLevel: VisibilityRuleDtoVisibilityLevel;
  maskType?: VisibilityRuleDtoMaskType;
  conditionJson?: VisibilityRuleDtoConditionJson;
}
